OrCS: vima_vector_t Class Reference
vima_vector_t Class Reference
#include <vima_vector.hpp>
Public Member Functions
vima_vector_t ()
~vima_vector_t ()
void clock ()
void allocate ()
void print_vector ()
bool ready ()
Public Attributes
package_state_t status
uint64_t tag
uint64_t lru
bool dirty
uint64_t fetch_start
uint64_t fetch_count
uint64_t fetch_latency_total
uint64_t writeback_start
uint64_t writeback_count
uint64_t writeback_latency_total
Private Attributes
memory_package_t * sub_requests
uint32_t no_sub_requests
uint32_t sub_ready
uint64_t address
uint64_t next_address
uint64_t sub_req_offset
uint64_t set
uint64_t column
uint32_t LINE_SIZE
uint32_t VIMA_VECTOR_SIZE
Detailed Description
Definition at line 1 of file vima_vector.hpp.
Constructor & Destructor Documentation
vima_vector_t()
vima_vector_t::vima_vector_t ()
Definition at line 4 of file vima_vector.cpp.
{
    this->no_sub_requests = 0;
    this->sub_ready = 0;
    this->address = 0;
    this->next_address = 0;
    this->sub_req_offset = 0;
    this->sub_requests = NULL;
    this->LINE_SIZE = 0;
    this->VIMA_VECTOR_SIZE = 0;
    status = PACKAGE_STATE_FREE;
    this->tag = 0;
    this->lru = 0;
    this->dirty = false;
}
References address, dirty, LINE_SIZE, lru, next_address, no_sub_requests, PACKAGE_STATE_FREE, status, sub_ready, sub_req_offset, sub_requests, tag, and VIMA_VECTOR_SIZE.
~vima_vector_t()
vima_vector_t::~vima_vector_t ()
Definition at line 20 of file vima_vector.cpp.
{
    delete[] sub_requests;
}
References sub_requests.
Member Function Documentation
allocate()
void vima_vector_t::allocate ()
Definition at line 125 of file vima_vector.cpp.
{
    libconfig::Setting &cfg_root = orcs_engine.configuration->getConfig();
    libconfig::Setting &cfg_processor = cfg_root["VIMA_CONTROLLER"];
    libconfig::Setting &cfg_cache_defs = cfg_root["CACHE_MEMORY"];
    set_LINE_SIZE(cfg_cache_defs["CONFIG"]["LINE_SIZE"]);
    set_VIMA_VECTOR_SIZE (cfg_processor["VIMA_VECTOR_SIZE"]);
    set_no_sub_requests (get_VIMA_VECTOR_SIZE()/get_LINE_SIZE());
    this->sub_requests = new memory_package_t[this->no_sub_requests]();
    for (size_t i = 0; i < get_no_sub_requests(); i++) {
        sub_requests[i].is_vima = true;
        sub_requests[i].status = PACKAGE_STATE_FREE;
    }
    status = PACKAGE_STATE_FREE;
    sub_ready = no_sub_requests;
    sub_req_offset = utils_t::get_power_of_two(LINE_SIZE);
}
References orcs_engine_t::configuration, utils_t::get_power_of_two(), configure_t::getConfig(), memory_package_t::is_vima, LINE_SIZE, no_sub_requests, orcs_engine, PACKAGE_STATE_FREE, memory_package_t::status, status, sub_ready, sub_req_offset, and sub_requests.
clock()
void vima_vector_t::clock ()
Definition at line 28 of file vima_vector.cpp.
{
    //if (address == 0 && next_address != 0) address = next_address;
    switch (status){
        case PACKAGE_STATE_TRANSMIT:
            //writeback
            if (dirty) {
                if (sub_ready == no_sub_requests){
                    #if VIMA_DEBUG
                        ORCS_PRINTF ("%lu VIMA Cache [%lu][%lu] WRITEBACK of address %lu, lru = %lu STARTED!\n", orcs_engine.get_global_cycle(), this->set, this->column, this->address, this->lru)
                    #endif
                    this->writeback_start = orcs_engine.get_global_cycle();
                    this->writeback_count++;
                    sub_ready = 0;
                    for (uint32_t i = 0; i < get_no_sub_requests(); i++){
                        sub_requests[i].memory_operation = MEMORY_OPERATION_WRITE;
                        sub_requests[i].status = PACKAGE_STATE_UNTREATED;
                        sub_requests[i].sent_to_ram = false;
                        sub_requests[i].row_buffer = false;
                        sub_requests[i].memory_address = address + i*this->get_LINE_SIZE();
                        sub_requests[i].born_cycle = orcs_engine.get_global_cycle();
                        orcs_engine.memory_controller->requestDRAM (&sub_requests[i]);
                    }
                } else {
                    while (sub_ready < no_sub_requests &&
                        sub_requests[sub_ready].status == PACKAGE_STATE_WAIT &&
                        sub_requests[sub_ready].readyAt <= orcs_engine.get_global_cycle()) sub_ready++;
                }
                if (sub_ready >= no_sub_requests) {
                    #if VIMA_DEBUG
                        ORCS_PRINTF ("%lu VIMA Cache [%lu][%lu] WRITEBACK of address %lu FINISHED! Took %lu cycles.\n", orcs_engine.get_global_cycle(), this->set, this->column, this->address, (orcs_engine.get_global_cycle() - this->writeback_start))
                    #endif
                    this->writeback_latency_total += (orcs_engine.get_global_cycle() - this->writeback_start);
                    status = PACKAGE_STATE_WAIT;
                }
            } else status = PACKAGE_STATE_WAIT;
            //setar todas as instruções para STORE
            //enviar todas as instruções para a DRAM
            //contar quantas estão prontas
            //if contagem == total, torna-se WAIT
            break;
        case PACKAGE_STATE_WAIT:
            //fetch
            if (this->next_address != 0){
                this->address = this->next_address;
                //this->next_address = 0;
                if (sub_ready == no_sub_requests){
                    #if VIMA_DEBUG
                        ORCS_PRINTF ("%lu VIMA Cache [%lu][%lu] FETCH of address %lu STARTED!\n", orcs_engine.get_global_cycle(), this->set, this->column, this->address)
                    #endif
                    this->fetch_start = orcs_engine.get_global_cycle();
                    this->fetch_count++;
                    sub_ready = 0;
                    for (uint32_t i = 0; i < get_no_sub_requests(); i++){
                        sub_requests[i].memory_operation = MEMORY_OPERATION_READ;
                        sub_requests[i].status = PACKAGE_STATE_UNTREATED;
                        sub_requests[i].sent_to_ram = false;
                        sub_requests[i].row_buffer = false;
                        sub_requests[i].memory_address = address + i*this->get_LINE_SIZE();
                        sub_requests[i].born_cycle = orcs_engine.get_global_cycle();
                        orcs_engine.memory_controller->requestDRAM (&sub_requests[i]);
                    }
                } else {
                    while (sub_ready < no_sub_requests &&
                            sub_requests[sub_ready].status == PACKAGE_STATE_WAIT &&
                            sub_requests[sub_ready].readyAt <= orcs_engine.get_global_cycle()) sub_ready++;
                }
                if (sub_ready >= no_sub_requests) {
                    #if VIMA_DEBUG
                        ORCS_PRINTF ("%lu VIMA Cache [%lu][%lu] FETCH of address %lu FINISHED! Took %lu cycles.\n", orcs_engine.get_global_cycle(), this->set, this->column, this->address, (orcs_engine.get_global_cycle() - this->fetch_start))
                    #endif
                    this->fetch_latency_total += (orcs_engine.get_global_cycle() - this->fetch_start);
                    dirty = false;
                    lru = orcs_engine.get_global_cycle();
                    status = PACKAGE_STATE_READY;
                }
            } else {
                dirty = false;
                lru = orcs_engine.get_global_cycle();
                status = PACKAGE_STATE_READY;
            }
            //setar os novos endereços das instruções
            //setar todas as instruções para LOAD
            //enviar todas as instruções para  DRAM
            //contar quantas estão prontas
            //if contagem == total, torna-se READY
            break;
        default:
            break;
    }
}
References address, memory_package_t::born_cycle, dirty, fetch_count, fetch_latency_total, fetch_start, orcs_engine_t::get_global_cycle(), lru, memory_package_t::memory_address, orcs_engine_t::memory_controller, memory_package_t::memory_operation, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, next_address, no_sub_requests, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_READY, PACKAGE_STATE_TRANSMIT, PACKAGE_STATE_UNTREATED, PACKAGE_STATE_WAIT, memory_controller_t::requestDRAM(), memory_package_t::row_buffer, memory_package_t::sent_to_ram, memory_package_t::status, status, sub_ready, sub_requests, writeback_count, writeback_latency_total, and writeback_start.
print_vector()
void vima_vector_t::print_vector ()
Definition at line 24 of file vima_vector.cpp.
{
    ORCS_PRINTF ("VIMA Vector: address %lu, tag %lu, lru %lu, %s\n", address, tag, lru, get_enum_package_state_char (status))
}
References address, get_enum_package_state_char(), lru, ORCS_PRINTF, status, and tag.
ready()
bool vima_vector_t::ready ()
Definition at line 120 of file vima_vector.cpp.
{
    if (sub_ready >= no_sub_requests && status == PACKAGE_STATE_READY) return true;
    else return false;
}
References no_sub_requests, PACKAGE_STATE_READY, status, and sub_ready.
The documentation for this class was generated from the following files:
vima/vima_vector.hpp
vima/vima_vector.cpp