OrCS: trace_reader_t Class Reference
trace_reader_t Class Reference
#include <trace_reader.hpp>
Public Member Functions
trace_reader_t ()
Methods.
~trace_reader_t ()
void allocate (char *trace_file_name)
void statistics ()
void get_total_bbls ()
Generate the static dictionary.
void define_binary_bbl_size ()
void generate_binary_dict ()
bool trace_string_to_opcode (char *input_string, opcode_package_t *opcode)
bool trace_next_dynamic (uint32_t *next_bbl)
bool trace_next_memory (uint64_t *next_address, uint32_t *operation_size, bool *is_read)
bool pin_next (opcode_package_t *m)
bool trace_fetch (opcode_package_t *m)
uint64_t get_trace_size ()
Get the total number of opcodes.
Public Attributes
uint64_t processor_id
uint64_t address_translation
Private Attributes
gzFile gzStaticTraceFile
gzFile gzDynamicTraceFile
gzFile gzMemoryTraceFile
bool is_inside_bbl
Control the trace reading.
uint32_t currect_bbl
uint32_t currect_opcode
uint32_t binary_total_bbls
Control the static dictionary.
uint32_t * binary_bbl_size
Total of BBLs for the static file.
opcode_package_t ** binary_dict
Total of instructions for each BBL.
uint64_t fetch_instructions
Complete dictionary of BBLs and instructions.
uint64_t trace_opcode_max
char * line_static
char ** line_dynamic
char ** line_memory
Detailed Description
Definition at line 3 of file trace_reader.hpp.
Constructor & Destructor Documentation
trace_reader_t()
trace_reader_t::trace_reader_t ()
Methods.
Control the trace reading
Control the static dictionary
Total of BBLs for the static file
Total of instructions for each BBL
Complete dictionary of BBLs and instructions
Definition at line 4 of file trace_reader.cpp.
{
    this->line_static = NULL;
    this->line_dynamic = NULL;
    this->line_memory = NULL;
    //Trace Files
    this->gzStaticTraceFile = NULL;
    this->gzDynamicTraceFile = NULL;
    this->gzMemoryTraceFile = NULL;
    this->is_inside_bbl=NULL;
    this->currect_bbl=0;
    this->currect_opcode=0;
    this->binary_total_bbls = 0;
    this->binary_bbl_size = NULL;
    this->binary_dict = NULL;
    this->fetch_instructions=0;
        //get total opcodes
    this->trace_opcode_max=0;
}
References binary_bbl_size, binary_dict, binary_total_bbls, currect_bbl, currect_opcode, fetch_instructions, gzDynamicTraceFile, gzMemoryTraceFile, gzStaticTraceFile, is_inside_bbl, line_dynamic, line_memory, line_static, and trace_opcode_max.
~trace_reader_t()
trace_reader_t::~trace_reader_t ()
De-Allocate memory to prevent memory leak
Definition at line 30 of file trace_reader.cpp.
{
        if(orcs_engine.use_pin)
            return;
        gzclose(gzStaticTraceFile);
        gzclose(gzDynamicTraceFile);
        gzclose(gzMemoryTraceFile);
        utils_t::template_delete_array<char>(line_static);
        utils_t::template_delete_matrix<char>(line_dynamic, TRACE_LINE_SIZE);
        utils_t::template_delete_matrix<char>(line_memory, TRACE_LINE_SIZE);
        for (uint32_t bbl = 1; bbl < this->binary_total_bbls; bbl++) delete[] binary_dict[bbl];
        delete[] binary_dict;
        delete[] binary_bbl_size;
}
References binary_bbl_size, binary_dict, binary_total_bbls, gzDynamicTraceFile, gzMemoryTraceFile, gzStaticTraceFile, line_dynamic, line_memory, line_static, orcs_engine, TRACE_LINE_SIZE, and orcs_engine_t::use_pin.
Member Function Documentation
allocate()
void trace_reader_t::allocate (char * trace_file_name)
Open the Static Trace File
Open the .gz file
Open the Dynamic Trace File
Open the .gz group
Open the Memory Trace File
Open the .gz group
Set the trace_reader controls
Obtain the number of BBLs
Allocate the vector of BBL sizes
Initialize
Define the size of each specific BBL
Create the opcode for each BBL
Setting structures to count number of opcodes
total number of opcodes
translation Address
Definition at line 47 of file trace_reader.cpp.
{
    if(orcs_engine.use_pin) {
        return;
    }
    char file_name[TRACE_LINE_SIZE];
    // =================================================================
    // =================================================================
    file_name[0] = '\0';
    snprintf(file_name, sizeof(file_name), "%s.tid%d.stat.out.gz", trace_file, 0);
    DEBUG_PRINTF("Static File = %s => READY !\n", file_name);
    this->gzStaticTraceFile = gzopen(file_name, "ro");
    ERROR_ASSERT_PRINTF(gzStaticTraceFile != NULL, "Could not open the static file.\n%s\n", file_name);
    DEBUG_PRINTF("Static File = %s => READY !\n", file_name);
    // =================================================================
    // =================================================================
    file_name[0] = '\0';
    snprintf(file_name, sizeof(file_name), "%s.tid%lu.dyn.out.gz", trace_file, this->processor_id);
    this->gzDynamicTraceFile = gzopen(file_name, "ro");
    ERROR_ASSERT_PRINTF(this->gzDynamicTraceFile != NULL, "Could not open the dynamic file.\n%s\n", file_name);
    DEBUG_PRINTF("Dynamic File = %s => READY !\n", file_name);
    // =================================================================
    // =================================================================
    file_name[0] = '\0';
    snprintf(file_name, sizeof(file_name), "%s.tid%lu.mem.out.gz", trace_file, this->processor_id);
    this->gzMemoryTraceFile = gzopen(file_name, "ro");
    ERROR_ASSERT_PRINTF(this->gzMemoryTraceFile != NULL, "Could not open the memory file.\n%s\n", file_name);
    DEBUG_PRINTF("Memory File = %s => READY !\n", file_name);
    this->is_inside_bbl = false;
    this->currect_bbl = 0;
    this->currect_opcode = 0;
    this->get_total_bbls();
    this->binary_bbl_size = new uint32_t[this->binary_total_bbls]();
    ERROR_ASSERT_PRINTF(this->binary_bbl_size != NULL, "Could not allocate memory\n");
    for (uint32_t bbl = 0; bbl < this->binary_total_bbls; bbl++) {
        this->binary_bbl_size[bbl] = 0;
    }
    this->define_binary_bbl_size();
    this->binary_dict = new opcode_package_t*[this->binary_total_bbls]();
    ERROR_ASSERT_PRINTF(this->binary_dict != NULL, "Could not allocate memory\n");
    for (uint32_t bbl = 1; bbl < this->binary_total_bbls; bbl++) {
        this->binary_dict[bbl] = new opcode_package_t[this->binary_bbl_size[bbl]]();
        ERROR_ASSERT_PRINTF(this->binary_dict[bbl] != NULL, "Could not allocate memory\n");
    }
    this->generate_binary_dict();
    // ====================================================================
    // ====================================================================
    this->line_static = utils_t::template_allocate_array<char>(TRACE_LINE_SIZE);
    this->line_dynamic = utils_t::template_allocate_matrix<char>(1, TRACE_LINE_SIZE);
    this->line_memory = utils_t::template_allocate_matrix<char>(1, TRACE_LINE_SIZE);
    // ====================================================================
    this->trace_opcode_max=0;
    this->trace_opcode_max=this->get_trace_size();
    // ====================================================================
    //this->address_translation =  this->get_processor_id() << 56;
    this->address_translation =  0;
    // ====================================================================
}
References address_translation, binary_bbl_size, binary_dict, binary_total_bbls, currect_bbl, currect_opcode, DEBUG_PRINTF, define_binary_bbl_size(), ERROR_ASSERT_PRINTF, generate_binary_dict(), get_total_bbls(), get_trace_size(), gzDynamicTraceFile, gzMemoryTraceFile, gzStaticTraceFile, is_inside_bbl, line_dynamic, line_memory, line_static, orcs_engine, processor_id, TRACE_LINE_SIZE, trace_opcode_max, and orcs_engine_t::use_pin.
define_binary_bbl_size()
void trace_reader_t::define_binary_bbl_size ()
Go to the Begin of the File
Check is file not EOF
If Comment, then ignore
Definition at line 185 of file trace_reader.cpp.
{
    char file_line[TRACE_LINE_SIZE] = "";
    bool file_eof = false;
    uint32_t bbl = 0;
    gzclearerr(this->gzStaticTraceFile);
    gzseek(this->gzStaticTraceFile, 0, SEEK_SET);
    file_eof = gzeof(this->gzStaticTraceFile);
    ERROR_ASSERT_PRINTF(!file_eof, "Static File Unexpected EOF.\n")
    while (!file_eof) {
        gzgets(this->gzStaticTraceFile, file_line, TRACE_LINE_SIZE);
        file_eof = gzeof(this->gzStaticTraceFile);
        if (file_line[0] == '\0' || file_line[0] == '#') {
            continue;
        }
        else if (file_line[0] == '@') {
            bbl++;
            binary_bbl_size[bbl] = 0;
        }
        else {
            binary_bbl_size[bbl]++;
        }
    }
}
References binary_bbl_size, ERROR_ASSERT_PRINTF, gzStaticTraceFile, and TRACE_LINE_SIZE.
generate_binary_dict()
void trace_reader_t::generate_binary_dict ()
Actual BBL (Index of the Vector)
Actual Opcode
Go to the Begin of the File
Check is file not EOF
If Comment, then ignore
If New BBL
Debug from previous BBL
If Inside BBL
Definition at line 213 of file trace_reader.cpp.
{
    char file_line[TRACE_LINE_SIZE] = "";
    bool file_eof = false;
    uint32_t BBL = 0;
    uint32_t opcode = 0;
    opcode_package_t NewOpcode;
    gzclearerr(this->gzStaticTraceFile);
    gzseek(this->gzStaticTraceFile, 0, SEEK_SET);
    file_eof = gzeof(this->gzStaticTraceFile);
    ERROR_ASSERT_PRINTF(!file_eof, "Static File Unexpected EOF.\n")
    while (!file_eof) {
        gzgets(this->gzStaticTraceFile, file_line, TRACE_LINE_SIZE);
        file_eof = gzeof(this->gzStaticTraceFile);
        DEBUG_PRINTF("Read: %s\n", file_line);
        if (file_line[0] == '\0' || file_line[0] == '#') {
            continue;
        }
        else if (file_line[0] == '@') {
            DEBUG_PRINTF("BBL %u with %u instructions.\n", BBL, opcode);
            opcode = 0;
            BBL = (uint32_t)strtoul(file_line + 1, NULL, 10);
            ERROR_ASSERT_PRINTF(BBL < this->binary_total_bbls, "Static has more BBLs than previous analyzed static file.\n");
        }
        else {
            DEBUG_PRINTF("Opcode %u = %s", opcode, file_line);
            this->trace_string_to_opcode(file_line, &this->binary_dict[BBL][opcode]);
            ERROR_ASSERT_PRINTF(this->binary_dict[BBL][opcode].opcode_address != 0, "Static trace file generating opcode address equal to zero.\n")
            opcode++;
        }
    }
}
References binary_dict, binary_total_bbls, DEBUG_PRINTF, ERROR_ASSERT_PRINTF, gzStaticTraceFile, TRACE_LINE_SIZE, and trace_string_to_opcode().
get_total_bbls()
void trace_reader_t::get_total_bbls ()
Generate the static dictionary.
Go to the Begin of the File
Check is file not EOF
Definition at line 159 of file trace_reader.cpp.
{
    char file_line[TRACE_LINE_SIZE] = "";
    bool file_eof = false;
    uint32_t bbl = 0;
    this->binary_total_bbls = 0;
    gzclearerr(this->gzStaticTraceFile);
    gzseek(this->gzStaticTraceFile, 0, SEEK_SET);
    file_eof = gzeof(this->gzStaticTraceFile);
    ERROR_ASSERT_PRINTF(!file_eof, "Static File Unexpected EOF.\n")
    while (!file_eof) {
        gzgets(this->gzStaticTraceFile, file_line, TRACE_LINE_SIZE);
        file_eof = gzeof(this->gzStaticTraceFile);
        if (file_line[0] == '@') {
            bbl = (uint32_t)strtoul(file_line + 1, NULL, 10);
            this->binary_total_bbls++;
            ERROR_ASSERT_PRINTF(bbl == this->binary_total_bbls, "Expected sequenced bbls.\n")
        }
    }
    this->binary_total_bbls++;
}
References binary_total_bbls, ERROR_ASSERT_PRINTF, gzStaticTraceFile, and TRACE_LINE_SIZE.
get_trace_size()
uint64_t trace_reader_t::get_trace_size ()
Get the total number of opcodes.
Go to the Begin of the File
Check is file not EOF
Go to the Begin of the File
Definition at line 132 of file trace_reader.cpp.
{
   bool file_eof = false;
    uint32_t BBL = 0;
    uint64_t trace_size = 0;
    gzclearerr(this->gzDynamicTraceFile);
    gzseek(this->gzDynamicTraceFile, 0, SEEK_SET);
    file_eof = gzeof(this->gzDynamicTraceFile);
    ERROR_ASSERT_PRINTF(!file_eof, "Dynamic File Unexpected EOF.\n")
    while (!file_eof) {
        gzgets(this->gzDynamicTraceFile, this->line_dynamic[0], TRACE_LINE_SIZE);
        file_eof = gzeof(this->gzDynamicTraceFile);
        if (this->line_dynamic[0][0] != '\0' && this->line_dynamic[0][0] != '#' && this->line_dynamic[0][0] != '$') {
            BBL = (uint32_t)strtoul(this->line_dynamic[0], NULL, 10);
            trace_size += this->binary_bbl_size[BBL];
        }
    }
    gzclearerr(this->gzDynamicTraceFile);
    gzseek(this->gzDynamicTraceFile, 0, SEEK_SET);
    return(trace_size);
}
References binary_bbl_size, ERROR_ASSERT_PRINTF, gzDynamicTraceFile, line_dynamic, and TRACE_LINE_SIZE.
pin_next()
bool trace_reader_t::pin_next (opcode_package_t * m)
Read 1
Read 2
Write
Branches
Definition at line 467 of file trace_reader.cpp.
{
    char next_instruction[1024];
    char *tmp_ptr = NULL;
    char *sub_string = NULL;
    opcode_package_t CleanOpcode;
    if(fgets(next_instruction, 1024, stdin) == NULL) {
        ORCS_PRINTF("Could not read Pin input\n");
        return FAIL;
    }
    if(strcmp(next_instruction, "000") == 0) {
        return FAIL;
    }
    *m = CleanOpcode;
    sub_string = strtok_r(next_instruction, " ", &tmp_ptr);
    strcpy(m->opcode_assembly, sub_string);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->opcode_operation = static_cast<instruction_operation_t> (std::strtoul(sub_string, NULL, 10));
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->opcode_address = std::strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->opcode_size = std::strtoul(sub_string, NULL, 10);
    for (int i = 0; i < MAX_REGISTERS; ++i) {
        sub_string = strtok_r(NULL, " ", &tmp_ptr);
        m->read_regs[i] = std::atoi(sub_string);
        sub_string = strtok_r(NULL, " ", &tmp_ptr);
        m->write_regs[i] = std::atoi(sub_string);
    }
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->base_reg = std::strtoul(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->index_reg = std::strtoul(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_read = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->read_address = std::strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->read_size = std::strtoul(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_read2 = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->read2_address = std::strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->read2_size = std::strtoul(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_write = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->write_address = std::strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->write_size = std::strtoul(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->branch_type = static_cast<branch_t> (strtoull(sub_string, NULL, 10));
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_indirect = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_predicated = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    m->is_prefetch = (sub_string[0] == '1');
    this->fetch_instructions++;
    return OK;
}
References opcode_package_t::base_reg, opcode_package_t::branch_type, FAIL, fetch_instructions, opcode_package_t::index_reg, opcode_package_t::is_indirect, opcode_package_t::is_predicated, opcode_package_t::is_prefetch, opcode_package_t::is_read, opcode_package_t::is_read2, opcode_package_t::is_write, MAX_REGISTERS, OK, opcode_package_t::opcode_address, opcode_package_t::opcode_assembly, opcode_package_t::opcode_operation, opcode_package_t::opcode_size, ORCS_PRINTF, opcode_package_t::read2_address, opcode_package_t::read2_size, opcode_package_t::read_address, opcode_package_t::read_regs, opcode_package_t::read_size, opcode_package_t::write_address, opcode_package_t::write_regs, and opcode_package_t::write_size.
statistics()
void trace_reader_t::statistics ()
Definition at line 635 of file trace_reader.cpp.
{
    bool close = false;
    FILE *output = stdout;
    if(orcs_engine.output_file_name != NULL){
        output = fopen(orcs_engine.output_file_name,"a+");
        close=true;
    }
    if (output != NULL){
            utils_t::largestSeparator(output);
            fprintf(output,"trace_reader_t\n");
            fprintf(output,"fetch_instructions: %lu\n", this->fetch_instructions);
            utils_t::largestSeparator(output);
        }
        if(close) fclose(output);
}
References fetch_instructions, utils_t::largestSeparator(), orcs_engine, and orcs_engine_t::output_file_name.
trace_fetch()
bool trace_reader_t::trace_fetch (opcode_package_t * m)
Fetch new BBL inside the dynamic file.
Fetch new INSTRUCTION inside the static file.
Add SiNUCA information
If it is LOAD/STORE -> Fetch new MEMORY inside the memory file
Definition at line 558 of file trace_reader.cpp.
{
    if(orcs_engine.use_pin)
    {
        return pin_next(m);
    }
    opcode_package_t NewOpcode;
    bool success;
    uint32_t new_BBL;
    // =================================================================
    // =================================================================
    if (!this->is_inside_bbl) {
        success = this->trace_next_dynamic(&new_BBL);
        if (success) {
            this->currect_bbl = new_BBL;
            this->currect_opcode = 0;
            this->is_inside_bbl = true;
        }
        else {
            ORCS_PRINTF("End of dynamic simulation trace\n");
            return FAIL;
        }
    }
    // =================================================================
    // =================================================================
    NewOpcode = this->binary_dict[this->currect_bbl][this->currect_opcode];
    DEBUG_PRINTF("BBL:%u  OPCODE:%u = %s\n",this->currect_bbl, this->currect_opcode, NewOpcode.opcode_assembly);
    this->currect_opcode++;
    if (this->currect_opcode >= this->binary_bbl_size[this->currect_bbl]) {
        this->is_inside_bbl = false;
        this->currect_opcode = 0;
    }
    // =================================================================
    // =================================================================
    *m = NewOpcode;
    m->opcode_address |= this->address_translation;
    // =========================================================================
    // =========================================================================
    bool mem_is_read;
    if (m->is_read) {
        trace_next_memory(&m->read_address, &m->read_size, &mem_is_read);
        m->read_address |= this->address_translation;
        //ORCS_PRINTF ("read1: %lu | ", m->read_address)
        ERROR_ASSERT_PRINTF(mem_is_read == true, "Expecting a read from memory trace\n");
    }
    if (m->is_read2) {
        trace_next_memory(&m->read2_address, &m->read2_size, &mem_is_read);
        m->read2_address |= this->address_translation;
        //ORCS_PRINTF ("read2: %lu | ", m->read2_address)
        ERROR_ASSERT_PRINTF(mem_is_read == true, "Expecting a read2 from memory trace\n");
    }
    if (m->is_write) {
        trace_next_memory(&m->write_address, &m->write_size, &mem_is_read);
        m->write_address |= this->address_translation;
        //ORCS_PRINTF ("write: %lu | ", m->write_address)
        ERROR_ASSERT_PRINTF(mem_is_read == false, "Expecting a write from memory trace\n");
    }
    //if (m->is_read || m->is_read2 || m->is_write) ORCS_PRINTF (" operation = %s \n", get_enum_instruction_operation_char (m->opcode_operation))
    this->fetch_instructions++;
    return OK;
}
References address_translation, binary_bbl_size, binary_dict, currect_bbl, currect_opcode, DEBUG_PRINTF, ERROR_ASSERT_PRINTF, FAIL, fetch_instructions, is_inside_bbl, opcode_package_t::is_read, opcode_package_t::is_read2, opcode_package_t::is_write, OK, opcode_package_t::opcode_address, opcode_package_t::opcode_assembly, orcs_engine, ORCS_PRINTF, pin_next(), opcode_package_t::read2_address, opcode_package_t::read2_size, opcode_package_t::read_address, opcode_package_t::read_size, trace_next_dynamic(), trace_next_memory(), orcs_engine_t::use_pin, opcode_package_t::write_address, and opcode_package_t::write_size.
trace_next_dynamic()
bool trace_reader_t::trace_next_dynamic (uint32_t * next_bbl)
Obtain the next trace line
Analyze the trace line
BBL is always greater than 0 If strtoul==0 the line could not be converted.
Definition at line 361 of file trace_reader.cpp.
{
    static char file_line[TRACE_LINE_SIZE];
    file_line[0] = '\0';
    bool valid_dynamic = false;
    *next_bbl = 0;
    while (!valid_dynamic) {
        if (gzeof(this->gzDynamicTraceFile)) {
            return FAIL;
        }
        char *buffer = gzgets(this->gzDynamicTraceFile, file_line, TRACE_LINE_SIZE);
        if (buffer == NULL) {
            return FAIL;
        }
        if (file_line[0] == '\0' || file_line[0] == '#') {
            DEBUG_PRINTF("Dynamic trace line (empty/comment): %s\n", file_line);
            continue;
        }
        else if (file_line[0] == '$') {
            DEBUG_PRINTF("Dynamic trace line (synchronization): %s\n", file_line);
            continue;
        }
        else {
            DEBUG_PRINTF("Dynamic trace line: %s\n", file_line);
            *next_bbl = strtoul(file_line, NULL, 10);
            ERROR_ASSERT_PRINTF(*next_bbl != 0, "The BBL from the dynamic trace file should not be zero. Dynamic line %s\n", file_line);
            valid_dynamic = true;
        }
    }
    return OK;
}
References DEBUG_PRINTF, ERROR_ASSERT_PRINTF, FAIL, gzDynamicTraceFile, OK, and TRACE_LINE_SIZE.
trace_next_memory()
bool trace_reader_t::trace_next_memory (uint64_t * mem_address, uint32_t * mem_size, bool * mem_is_read)
Convert Dynamic Memory Trace line into Instruction Memory Operands Field #: 1 | 2 | 3 | 4 Type: R/W | R/W | Memory | BBL Op. | Size | Address | Number
Memory File Example:
#
Compressed Trace Generated By Pin to SiNUCA
# W 8 140735291283448 1238 W 8 140735291283440 1238 W 8 140735291283432 1238
Obtain the next trace line
Analyze the trace line
Definition at line 416 of file trace_reader.cpp.
{
    static char file_line[TRACE_LINE_SIZE];
    file_line[0] = '\0';
    bool valid_memory = false;
    while (!valid_memory) {
        if (gzeof(this->gzMemoryTraceFile)) {
            return FAIL;
        }
        char *buffer = gzgets(this->gzMemoryTraceFile, file_line, TRACE_LINE_SIZE);
        if (buffer == NULL) {
            return FAIL;
        }
        //ORCS_PRINTF ("processor %lu | %s", processor_id, file_line)
        if (file_line[0] == '\0' || file_line[0] == '#') {
            DEBUG_PRINTF("Memory trace line (empty/comment): %s\n", file_line);
            continue;
        }
        else {
            char *sub_string = NULL;
            char *tmp_ptr = NULL;
            uint32_t count = 0, i = 0;
            while (file_line[i] != '\0') {
                count += (file_line[i] == ' ');
                i++;
            }
            ERROR_ASSERT_PRINTF(count == 3, "Error converting Text to Memory (Wrong  number of fields %d)\n", count)
            DEBUG_PRINTF("Memory trace line: %s\n", file_line);
            sub_string = strtok_r(file_line, " ", &tmp_ptr);
            *mem_is_read = strcmp(sub_string, "R") == 0;
            sub_string = strtok_r(NULL, " ", &tmp_ptr);
            *mem_size = strtoull(sub_string, NULL, 10);
            sub_string = strtok_r(NULL, " ", &tmp_ptr);
            *mem_address = strtoull(sub_string, NULL, 10);
            sub_string = strtok_r(NULL, " ", &tmp_ptr);
            valid_memory = true;
        }
    }
    return OK;
}
References DEBUG_PRINTF, ERROR_ASSERT_PRINTF, FAIL, gzMemoryTraceFile, OK, and TRACE_LINE_SIZE.
trace_string_to_opcode()
bool trace_reader_t::trace_string_to_opcode (char * input_string, opcode_package_t * opcode)
Convert Static Trace line into Instruction Field #: 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 Type: Asm | Opcode | Inst. | Inst. | #Read | Read | #Write | Write | Base | Index | Is | Is | Is | Cond. | Is | Is | Is Cmd | Number | Addr. | Size | Regs | Regs | Regs | Regs | Reg. | Reg. | Read | Read2 | Write | Type | Indirect | Predicated | Pfetch
Static File Example:
#
Compressed Trace Generated By Pin to SiNUCA
# @1 MOV 8 4345024 3 1 12 1 19 12 0 1 3 0 0 0 0 0 ADD 1 4345027 4 1 12 2 12 34 0 0 3 0 0 0 0 0 0 TEST 1 4345031 3 2 19 19 1 34 0 0 3 0 0 0 0 0 0 JNZ 7 4345034 2 2 35 34 1 35 0 0 4 0 0 0 1 0 0 @2 CALL_NEAR 9 4345036 5 2 35 15 2 35 15 15 0 1 0 0 1 0 0 0
Number of Read Registers
Number of Write Registers
Definition at line 268 of file trace_reader.cpp.
{
    char *sub_string = NULL;
    char *tmp_ptr = NULL;
    uint32_t sub_fields, count, i;
    count = 0;
    for (i = 0; input_string[i] != '\0'; i++) {
        count += (input_string[i] == ' ');
    }
    ERROR_ASSERT_PRINTF(count >= 13, "Error converting Text to Instruction (Wrong  number of fields %d), input_string = %s\n", count, input_string)
    sub_string = strtok_r(input_string, " ", &tmp_ptr);
    strcpy(opcode->opcode_assembly, sub_string);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->opcode_operation = instruction_operation_t(strtoul(sub_string, NULL, 10));
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->opcode_address = strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->opcode_size = strtoul(sub_string, NULL, 10);
// =============
// Setting init values to read and write regs
// =============
    memset(opcode->read_regs, POSITION_FAIL, sizeof(int32_t) * MAX_REGISTERS);
    memset(opcode->write_regs, POSITION_FAIL, sizeof(int32_t) * MAX_REGISTERS);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    sub_fields = strtoul(sub_string, NULL, 10);
    for (i = 0; i < sub_fields; i++) {
        sub_string = strtok_r(NULL, " ", &tmp_ptr);
        opcode->read_regs[i] = strtoul(sub_string, NULL, 10);
    }
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    sub_fields = strtoul(sub_string, NULL, 10);
    for (i = 0; i < sub_fields; i++) {
        sub_string = strtok_r(NULL, " ", &tmp_ptr);
        opcode->write_regs[i] = strtoul(sub_string, NULL, 10);
    }
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->base_reg = strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->index_reg = strtoull(sub_string, NULL, 10);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_read = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_read2 = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_write = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->branch_type = branch_t(strtoull(sub_string, NULL, 10));
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_indirect = (sub_string[0] == '1');
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_predicated = (sub_string[0] == '1');
    if (count < 17) return OK;
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->is_hive = (sub_string[0] == '1');
    if (!opcode->is_hive) return OK;
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->hive_read1 = atoi(&sub_string[0]);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->hive_read2 = atoi(&sub_string[0]);
    sub_string = strtok_r(NULL, " ", &tmp_ptr);
    opcode->hive_write = atoi(&sub_string[0]);
    return OK;
}
References opcode_package_t::base_reg, opcode_package_t::branch_type, ERROR_ASSERT_PRINTF, opcode_package_t::hive_read1, opcode_package_t::hive_read2, opcode_package_t::hive_write, opcode_package_t::index_reg, opcode_package_t::is_hive, opcode_package_t::is_indirect, opcode_package_t::is_predicated, opcode_package_t::is_read, opcode_package_t::is_read2, opcode_package_t::is_write, MAX_REGISTERS, OK, opcode_package_t::opcode_address, opcode_package_t::opcode_assembly, opcode_package_t::opcode_operation, opcode_package_t::opcode_size, POSITION_FAIL, opcode_package_t::read_regs, and opcode_package_t::write_regs.
The documentation for this class was generated from the following files:
trace_reader.hpp
trace_reader.cpp