OrCS: reorder_buffer_line_t Class Reference
reorder_buffer_line_t Class Reference
#include <reorder_buffer_line.hpp>
Public Member Functions
reorder_buffer_line_t ()
Control flag to remove robs entry.
~reorder_buffer_line_t ()
void package_clean ()
std::string content_to_string ()
std::string content_to_string2 ()
Static Public Member Functions
static std::string print_all (reorder_buffer_line_t *input_array, uint32_t size_array)
STATIC METHODS.
Public Attributes
uint32_t processor_id
uop_package_t uop
processor_stage_t stage
uint32_t wait_reg_deps_number
Register Dependencies Control.
reorder_buffer_line_t ** reg_deps_ptr_array
Must wait BEFORE execution.
uint32_t wake_up_elements_counter
Elements to wake-up AFTER execution.
memory_order_buffer_line_t * mob_ptr
Counter of elements to wakeup.
bool sent
mob pointer to memory request
Detailed Description
Definition at line 21 of file reorder_buffer_line.hpp.
Constructor & Destructor Documentation
reorder_buffer_line_t()
reorder_buffer_line_t::reorder_buffer_line_t ()
Control flag to remove robs entry.
Methods
Definition at line 25 of file reorder_buffer_line.cpp.
{
    this->package_clean();
    this->reg_deps_ptr_array = NULL;
}
References package_clean(), and reg_deps_ptr_array.
~reorder_buffer_line_t()
reorder_buffer_line_t::~reorder_buffer_line_t ()
Definition at line 31 of file reorder_buffer_line.cpp.
{
    utils_t::template_delete_array<reorder_buffer_line_t*>(reg_deps_ptr_array);
}
References reg_deps_ptr_array.
Member Function Documentation
content_to_string()
std::string reorder_buffer_line_t::content_to_string ()
Definition at line 47 of file reorder_buffer_line.cpp.
{
    std::string content_string;
    content_string = "";
    #ifndef SHOW_FREE_PACKAGE
        if (this->uop.status == PACKAGE_STATE_FREE) {
            return content_string;
        }
    #endif
    content_string = this->uop.content_to_string();
    content_string = content_string + " | Stage:" + get_enum_processor_stage_char(this->stage);
    content_string = content_string + " | Reg.Wait:" + utils_t::uint32_to_string(this->wait_reg_deps_number);
    content_string = content_string + " | WakeUp:" + utils_t::uint32_to_string(this->wake_up_elements_counter);
    content_string = content_string + " | ReadyAt: " + utils_t::uint64_to_string(this->uop.readyAt);
    content_string = content_string + " | Sent: " + utils_t::bool_to_string(this->sent);
    if(this->mob_ptr != NULL){
        content_string = content_string + this->mob_ptr->content_to_string();
    }
    return content_string;
}
References utils_t::bool_to_string(), uop_package_t::content_to_string(), memory_order_buffer_line_t::content_to_string(), get_enum_processor_stage_char(), mob_ptr, PACKAGE_STATE_FREE, uop_package_t::readyAt, sent, stage, uop_package_t::status, utils_t::uint32_to_string(), utils_t::uint64_to_string(), uop, wait_reg_deps_number, and wake_up_elements_counter.
content_to_string2()
std::string reorder_buffer_line_t::content_to_string2 ()
Definition at line 68 of file reorder_buffer_line.cpp.
{
    std::string content_string;
    content_string = "";
    #ifndef SHOW_FREE_PACKAGE
        if (this->uop.status == PACKAGE_STATE_FREE) {
            return content_string;
        }
    #endif
    content_string = this->uop.content_to_string();
    content_string = content_string + " | Stage:" + get_enum_processor_stage_char(this->stage);
    content_string = content_string + " | Reg.Wait:" + utils_t::uint32_to_string(this->wait_reg_deps_number);
    content_string = content_string + " | WakeUp:" + utils_t::uint32_to_string(this->wake_up_elements_counter);
    content_string = content_string + " | ReadyAt: " + utils_t::uint64_to_string(this->uop.readyAt);
    content_string = content_string + " | Sent: " + utils_t::bool_to_string(this->sent);
    return content_string;
}
References utils_t::bool_to_string(), uop_package_t::content_to_string(), get_enum_processor_stage_char(), PACKAGE_STATE_FREE, uop_package_t::readyAt, sent, stage, uop_package_t::status, utils_t::uint32_to_string(), utils_t::uint64_to_string(), uop, wait_reg_deps_number, and wake_up_elements_counter.
package_clean()
void reorder_buffer_line_t::package_clean ()
Definition at line 36 of file reorder_buffer_line.cpp.
{
    this->uop.package_clean();
    this->stage = PROCESSOR_STAGE_DECODE;
    this->mob_ptr = NULL;
    this->wait_reg_deps_number = 0;
    this->wake_up_elements_counter = 0;
    this->sent=false;
    this->processor_id=0;
    }
References mob_ptr, uop_package_t::package_clean(), processor_id, PROCESSOR_STAGE_DECODE, sent, stage, uop, wait_reg_deps_number, and wake_up_elements_counter.
print_all()
std::string reorder_buffer_line_t::print_all (reorder_buffer_line_t * input_array, uint32_t size_array) static
STATIC METHODS.
Definition at line 90 of file reorder_buffer_line.cpp.
{
    std::string content_string;
    std::string final_string;
    final_string = "";
    for (uint32_t i = 0; i < size_array ; i++) {
        content_string = "";
        content_string = input_array[i].content_to_string();
        if (content_string.size() > 1) {
            final_string = final_string + "[" + utils_t::uint32_to_string(i) + "] " + content_string + "\n";
        }
    }
    return final_string;
}
References content_to_string(), and utils_t::uint32_to_string().
The documentation for this class was generated from the following files:
processor/reorder_buffer_line.hpp
processor/reorder_buffer_line.cpp