OrCS: memory_package_t Class Reference
memory_package_t Class Reference
#include <memory_package.hpp>
Public Member Functions
memory_package_t ()
update these
~memory_package_t ()
void updatePackageUntreated (uint32_t stallTime)
void updatePackageReady ()
void updatePackageWait (uint32_t stallTime)
void updatePackageFree (uint32_t stallTime)
void updatePackageHive (uint32_t stallTime)
void updatePackageVima (uint32_t stallTime)
void updatePackageTransmit (uint32_t stallTime)
void updatePackageDRAMFetch (uint32_t stallTime)
void updatePackageDRAMReady (uint32_t stallTime)
void updateClients ()
void printPackage ()
Public Attributes
uint32_t processor_id
uint64_t opcode_number
if (read / write) PROCESSOR.ID else if (write-back / prefetch) CACHE_MEMORY.ID
uint64_t opcode_address
initial opcode number
uint64_t uop_number
initial opcode address
uint64_t memory_address
initial uop number (Instruction == 0)
uint32_t memory_size
memory address
package_state_t status
operation size after offset
uint64_t readyAt
package state
uint64_t born_cycle
package latency
uint64_t ram_cycle
package creation time
uint64_t vima_cycle
uint64_t hive_cycle
uint32_t next_level
uint32_t * sent_to_cache_level
uint32_t * sent_to_cache_level_at
uint32_t cache_latency
bool sent_to_ram
bool is_hive
int64_t hive_read1
int64_t hive_read2
int64_t hive_write
bool is_vima
uint64_t vima_read1
uint64_t vima_read2
uint64_t vima_write
bool row_buffer
cacheId_t type
uint64_t * op_count
uint32_t latency
memory_operation_t memory_operation
std::vector< memory_request_client_t * > clients
memory operation
Detailed Description
Definition at line 1 of file memory_package.hpp.
Constructor & Destructor Documentation
memory_package_t()
memory_package_t::memory_package_t ()
update these
if (read / write) PROCESSOR.ID else if (write-back / prefetch) CACHE_MEMORY.ID
initial opcode number
initial opcode address
initial uop number (Instruction == 0)
memory address
operation size after offset
package state
package latency
package create time
memory operation
Definition at line 4 of file memory_package.cpp.
{
    this->processor_id = 0;
    this->opcode_number = 0;
    this->opcode_address = 0;
    this->uop_number = 0;
    this->memory_address = 0;
    this->memory_size = 0;
    status = PACKAGE_STATE_FREE;
    this->readyAt = 0;
    this->born_cycle = 0;
    this->ram_cycle = 0;
    this->vima_cycle = 0;
    this->hive_cycle = 0;
    sent_to_ram = false;
    next_level = L1;
    cache_latency = 0;
    is_hive = false;
    hive_read1 = 0;
    hive_read2 = 0;
    hive_write = 0;
    this->is_vima = false;
    this->vima_read1 = 0;
    this->vima_read2 = 0;
    this->vima_write = 0;
    row_buffer = false;
    type = DATA;
    op_count = new uint64_t[MEMORY_OPERATION_LAST]();
    sent_to_cache_level = new uint32_t[END]();
    sent_to_cache_level_at = new uint32_t[END]();
    this->latency = 0;
    memory_operation = MEMORY_OPERATION_LAST;
}
References born_cycle, cache_latency, DATA, END, hive_cycle, hive_read1, hive_read2, hive_write, is_hive, is_vima, L1, latency, memory_address, memory_operation, MEMORY_OPERATION_LAST, memory_size, next_level, op_count, opcode_address, opcode_number, PACKAGE_STATE_FREE, processor_id, ram_cycle, readyAt, row_buffer, sent_to_cache_level, sent_to_cache_level_at, sent_to_ram, status, type, uop_number, vima_cycle, vima_read1, vima_read2, and vima_write.
~memory_package_t()
memory_package_t::~memory_package_t ()
Definition at line 42 of file memory_package.cpp.
{
    vector<memory_request_client_t*>().swap(this->clients);
    delete[] op_count;
    delete[] sent_to_cache_level;
    delete[] sent_to_cache_level_at;
}
References clients, op_count, sent_to_cache_level, and sent_to_cache_level_at.
Member Function Documentation
printPackage()
void memory_package_t::printPackage ()
Definition at line 156 of file memory_package.cpp.
{
    ORCS_PRINTF ("%lu Address: %lu | Operation: %s | Status: %s | Uop: %lu | ReadyAt: %lu\n", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status), uop_number, readyAt)
}
References get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), memory_address, memory_operation, orcs_engine, ORCS_PRINTF, readyAt, status, and uop_number.
updateClients()
void memory_package_t::updateClients ()
Definition at line 160 of file memory_package.cpp.
{
    for (size_t i = 0; i < clients.size(); i++) {
        clients[i]->updatePackageReady (0);
    }
}
References clients.
updatePackageDRAMFetch()
void memory_package_t::updatePackageDRAMFetch (uint32_t stallTime)
Definition at line 132 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_DRAM_FETCH;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_DRAM_FETCH, readyAt, and status.
updatePackageDRAMReady()
void memory_package_t::updatePackageDRAMReady (uint32_t stallTime)
Definition at line 144 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_DRAM_READY;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_DRAM_READY, readyAt, and status.
updatePackageFree()
void memory_package_t::updatePackageFree (uint32_t stallTime)
Definition at line 96 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_FREE;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_FREE, readyAt, and status.
updatePackageHive()
void memory_package_t::updatePackageHive (uint32_t stallTime)
Definition at line 108 of file memory_package.cpp.
{
    #if MEMORY_DEBUG || HIVE_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_HIVE;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG || HIVE_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_HIVE, readyAt, and status.
updatePackageReady()
void memory_package_t::updatePackageReady ()
Definition at line 61 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_READY;
    this->readyAt = orcs_engine.get_global_cycle();
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_READY, readyAt, and status.
updatePackageTransmit()
void memory_package_t::updatePackageTransmit (uint32_t stallTime)
Definition at line 84 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_TRANSMIT;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_TRANSMIT, readyAt, and status.
updatePackageUntreated()
void memory_package_t::updatePackageUntreated (uint32_t stallTime)
Definition at line 49 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_UNTREATED;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_UNTREATED, readyAt, and status.
updatePackageVima()
void memory_package_t::updatePackageVima (uint32_t stallTime)
Definition at line 120 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_VIMA;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_VIMA, readyAt, and status.
updatePackageWait()
void memory_package_t::updatePackageWait (uint32_t stallTime)
Definition at line 72 of file memory_package.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[MEMP] %lu %lu %s %s -> ", orcs_engine.get_global_cycle(), memory_address, get_enum_memory_operation_char (memory_operation), get_enum_package_state_char (status))
    #endif
    this->status = PACKAGE_STATE_WAIT;
    this->readyAt = orcs_engine.get_global_cycle() + stallTime;
    this->latency += stallTime;
    #if MEMORY_DEBUG
        ORCS_PRINTF ("%s, born: %lu, readyAt: %lu, latency: %u, stallTime: %u\n", get_enum_package_state_char (status), born_cycle, readyAt, latency, stallTime)
    #endif
}
References born_cycle, get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), latency, memory_address, memory_operation, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_WAIT, readyAt, and status.
The documentation for this class was generated from the following files:
package/memory_package.hpp
package/memory_package.cpp