OrCS: cache_manager_t Class Reference
cache_manager_t Class Reference
#include <cache_manager.hpp>
Public Member Functions
cache_manager_t ()
~cache_manager_t ()
void allocate (uint32_t NUMBER_OF_PROCESSORS)
void clock ()
void statistics (uint32_t core_id)
void generateIndexArray (uint32_t processor_id, int32_t *cache_indexes)
bool searchData (memory_package_t *mob_line)
bool available (uint32_t processor_id, memory_operation_t op)
Public Attributes
cache_t ** data_cache
cache_t ** instruction_cache
uint32_t * ICACHE_AMOUNT
uint32_t * DCACHE_AMOUNT
uint64_t ** op_count
uint64_t * op_max
prefetcher_t * prefetcher
Private Member Functions
cache_t ** instantiate_cache (cacheId_t cache_type, libconfig::Setting &cfg_cache_defs)
void get_cache_levels (cacheId_t cache_type, libconfig::Setting &cfg_cache_defs)
void get_cache_info (cacheId_t cache_type, libconfig::Setting &cfg_cache_defs, cache_t *cache, uint32_t cache_level, uint32_t CACHE_AMOUNT)
void check_cache (uint32_t cache_size, uint32_t cache_level)
void print_requests ()
bool isIn (memory_package_t *mob_line)
void installCacheLines (memory_package_t *request, int32_t *cache_indexes, uint32_t latency_request, cacheId_t cache_type)
uint32_t searchAddress (uint64_t instructionAddress, cache_t *cache, uint32_t *latency_request, uint32_t *ttc)
cache_status_t recursiveInstructionSearch (memory_package_t *mob_line, int32_t *cache_indexes, uint32_t latency_request, uint32_t ttc, uint32_t cache_level)
cache_status_t instructionSearch (memory_package_t *request, int32_t *cache_indexes, uint32_t latency_request, uint32_t ttc)
cache_status_t recursiveDataSearch (memory_package_t *mob_line, int32_t *cache_indexes, uint32_t latency_request, uint32_t ttc, uint32_t cache_level, cacheId_t cache_type)
cache_status_t dataSearch (memory_package_t *request, int32_t *cache_indexes, uint32_t latency_request, uint32_t ttc)
cache_status_t recursiveDataWrite (memory_package_t *mob_line, int32_t *cache_indexes, uint32_t latency_request, uint32_t ttc, uint32_t cache_level, cacheId_t cache_type)
cache_status_t cache_search (memory_package_t *request, cache_t *cache, int32_t *cache_indexes)
void process (memory_package_t *request, int32_t *cache)
void requestCache (memory_package_t *request)
void finishRequest (memory_package_t *request, int32_t *cache_indexes)
void install (memory_package_t *request)
Private Attributes
uint64_t i
uint64_t reads
uint64_t read_miss
uint64_t read_hit
uint64_t writes
uint64_t write_miss
uint64_t write_hit
uint64_t offset
uint64_t mshr_index
uint64_t min_sent_ram
uint64_t max_sent_ram
uint64_t sent_ram
uint64_t sent_ram_cycles
uint64_t sent_hive
uint64_t sent_hive_cycles
uint64_t sent_vima
uint64_t sent_vima_cycles
uint64_t max_vima
uint64_t * total_latency
uint64_t * total_operations
uint64_t * min_wait_operations
uint64_t * max_wait_operations
uint64_t wait_time
uint32_t LINE_SIZE
uint32_t PREFETCHER_ACTIVE
uint32_t DATA_LEVELS
uint32_t INSTRUCTION_LEVELS
uint32_t POINTER_LEVELS
uint32_t LLC_CACHES
uint32_t CACHE_MANAGER_DEBUG
uint32_t WAIT_CYCLE
uint32_t NUMBER_OF_PROCESSORS
uint32_t MAX_PARALLEL_REQUESTS_CORE
std::vector< memory_package_t * > requests
Detailed Description
Definition at line 5 of file cache_manager.hpp.
Constructor & Destructor Documentation
cache_manager_t()
cache_manager_t::cache_manager_t ()
Definition at line 4 of file cache_manager.cpp.
{
    this->i = 0;
    this->reads = 0;
    this->read_miss = 0;
    this->read_hit = 0;
    this->writes = 0;
    this->write_miss = 0;
    this->write_hit = 0;
    this->offset = 0;
    this->mshr_index = 0;
    this->sent_ram = 0;
    this->sent_ram_cycles = 0;
    this->sent_hive = 0;
    this->sent_hive_cycles = 0;
    this->sent_vima = 0;
    this->sent_vima_cycles = 0;
    this->max_vima = 0;
    this->LINE_SIZE = 0;
    this->PREFETCHER_ACTIVE = 0;
    this->DATA_LEVELS = 0;
    this->INSTRUCTION_LEVELS = 0;
    this->POINTER_LEVELS = 0;
    this->LLC_CACHES = 0;
    this->CACHE_MANAGER_DEBUG = 0;
    this->WAIT_CYCLE = 0;
    this->NUMBER_OF_PROCESSORS = 0;
    this->MAX_PARALLEL_REQUESTS_CORE = 0;
    data_cache = NULL;
    instruction_cache = NULL;
    ICACHE_AMOUNT = NULL;
    DCACHE_AMOUNT = NULL;
}
References CACHE_MANAGER_DEBUG, data_cache, DATA_LEVELS, DCACHE_AMOUNT, i, ICACHE_AMOUNT, instruction_cache, INSTRUCTION_LEVELS, LINE_SIZE, LLC_CACHES, MAX_PARALLEL_REQUESTS_CORE, max_vima, mshr_index, NUMBER_OF_PROCESSORS, offset, POINTER_LEVELS, PREFETCHER_ACTIVE, read_hit, read_miss, reads, sent_hive, sent_hive_cycles, sent_ram, sent_ram_cycles, sent_vima, sent_vima_cycles, WAIT_CYCLE, write_hit, write_miss, and writes.
~cache_manager_t()
cache_manager_t::~cache_manager_t ()
Definition at line 44 of file cache_manager.cpp.
{
    for (i = 0; i < this->requests.size(); i++) delete requests[i];
    delete[] this->total_operations;
    delete[] this->total_latency;
    delete[] this->min_wait_operations;
    delete[] this->max_wait_operations;
    for (uint32_t i = 0; i < INSTRUCTION_LEVELS; i++) delete[] instruction_cache[i];
    for (uint32_t i = 0; i < DATA_LEVELS; i++) delete[] data_cache[i];
    delete[] ICACHE_AMOUNT;
    delete[] DCACHE_AMOUNT;
    delete[] data_cache;
    delete[] instruction_cache;
    std::vector<memory_package_t *>().swap(requests);
}
References data_cache, DATA_LEVELS, DCACHE_AMOUNT, i, ICACHE_AMOUNT, instruction_cache, INSTRUCTION_LEVELS, max_wait_operations, min_wait_operations, requests, total_latency, and total_operations.
Member Function Documentation
allocate()
void cache_manager_t::allocate (uint32_t NUMBER_OF_PROCESSORS)
Definition at line 194 of file cache_manager.cpp.
{
    // Access configure file
    set_NUMBER_OF_PROCESSORS(NUMBER_OF_PROCESSORS);
    libconfig::Setting &cfg_root = orcs_engine.configuration->getConfig();
    // Get prefetcher info
    libconfig::Setting &prefetcher_defs = cfg_root["PREFETCHER"];
    set_PREFETCHER_ACTIVE(prefetcher_defs["PREFETCHER_ACTIVE"]);
    // Get general cache info
    libconfig::Setting &cfg_cache_defs = cfg_root["CACHE_MEMORY"];
    set_CACHE_MANAGER_DEBUG(cfg_cache_defs["CONFIG"]["CACHE_MANAGER_DEBUG"]);
    set_LINE_SIZE(cfg_cache_defs["CONFIG"]["LINE_SIZE"]);
    set_WAIT_CYCLE(cfg_cache_defs["CONFIG"]["WAIT_CYCLE"]);
    set_MAX_PARALLEL_REQUESTS_CORE(cfg_root["MEMORY_CONTROLLER"]["MAX_PARALLEL_REQUESTS_CORE"]);
    this->instruction_cache = this->instantiate_cache(INSTRUCTION, cfg_cache_defs);
    this->data_cache = this->instantiate_cache(DATA, cfg_cache_defs);
    set_POINTER_LEVELS((INSTRUCTION_LEVELS > DATA_LEVELS) ? INSTRUCTION_LEVELS : DATA_LEVELS);
    //set_POINTER_LEVELS(3);
    //Read/Write counters
    this->set_reads(0);
    this->set_read_hit(0);
    this->set_read_miss(0);
    this->set_writes(0);
    this->set_write_hit(0);
    this->set_write_miss(0);
    this->set_offset(utils_t::get_power_of_two(LINE_SIZE));
    this->set_min_sent_ram(UINT32_MAX);
    this->set_max_sent_ram(0);
    this->set_sent_ram(0);
    this->set_sent_ram_cycles(0);
    this->set_sent_hive(0);
    this->set_sent_hive_cycles(0);
    this->set_sent_vima(0);
    this->set_sent_vima_cycles(0);
    this->total_latency = new uint64_t [MEMORY_OPERATION_LAST]();
    this->total_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    this->min_wait_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    for (i = 0; i < MEMORY_OPERATION_LAST; i++) this->min_wait_operations[i] = UINT64_MAX;
    this->max_wait_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    //Allocate Prefetcher
    if (PREFETCHER_ACTIVE) {
        this->prefetcher = new prefetcher_t();
        this->prefetcher->allocate(NUMBER_OF_PROCESSORS);
    }
}
References prefetcher_t::allocate(), orcs_engine_t::configuration, DATA, data_cache, DATA_LEVELS, utils_t::get_power_of_two(), configure_t::getConfig(), i, instantiate_cache(), INSTRUCTION, instruction_cache, INSTRUCTION_LEVELS, LINE_SIZE, max_wait_operations, MEMORY_OPERATION_LAST, min_wait_operations, NUMBER_OF_PROCESSORS, orcs_engine, prefetcher, PREFETCHER_ACTIVE, total_latency, and total_operations.
available()
bool cache_manager_t::available (uint32_t processor_id, memory_operation_t op)
Definition at line 618 of file cache_manager.cpp.
{
    int32_t *cache_indexes = new int32_t[POINTER_LEVELS]();
    bool result = false;
    this->generateIndexArray(processor_id, cache_indexes);
    switch (op){
        case MEMORY_OPERATION_READ:
        case MEMORY_OPERATION_WRITE:
            result = this->data_cache[L1][cache_indexes[L1]].get_count() < this->data_cache[L1][cache_indexes[L1]].mshr_size;
        break;
        case MEMORY_OPERATION_INST:
            result = this->instruction_cache[L1][cache_indexes[L1]].get_count() < this->instruction_cache[L1][cache_indexes[L1]].mshr_size;
        break;
        default:
            ERROR_ASSERT_PRINTF (true, "WRONG MEMORY OPERATION TYPE")
        break;
    }
    delete[] cache_indexes;
    return result;
}
References data_cache, ERROR_ASSERT_PRINTF, generateIndexArray(), instruction_cache, L1, MEMORY_OPERATION_INST, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, cache_t::mshr_size, and POINTER_LEVELS.
cache_search()
cache_status_t cache_manager_t::cache_search (memory_package_t * request, cache_t * cache, int32_t * cache_indexes) private
Definition at line 568 of file cache_manager.cpp.
{
    #if PROCESSOR_DEBUG
        ORCS_PRINTF ("%lu Cache Manager cache_search(): memory = %lu | level = %u, type = %s, count = %u -> count = %u, %s, %lu\n", orcs_engine.get_global_cycle(), requests.size(), request->next_level, get_enum_cache_type_char ((cacheId_t) cache->id), cache->get_count(), cache->get_count()+1, get_enum_memory_operation_char (request->memory_operation), request->memory_address)
    #endif
    uint32_t cache_status = 0, ttc = 0;
    cache_status = this->searchAddress(request->memory_address, cache, &request->cache_latency, &ttc);
    cache->cache_count_per_type[request->memory_operation]++;
    request->sent_to_cache_level[request->next_level] = 1;
    request->sent_to_cache_level_at[request->next_level] = orcs_engine.get_global_cycle();
    if (cache_status == HIT) {
        #if MEMORY_DEBUG
            ORCS_PRINTF (" HIT!\n");
        #endif
        switch (request->memory_operation){
            case MEMORY_OPERATION_READ:
            case MEMORY_OPERATION_WRITE:
                if (request->next_level != 0) {
                    for (int32_t i = request->next_level - 1; i >= 0; i--) {
                        this->data_cache[i+1][cache_indexes[i+1]].returnLine(request, &this->data_cache[i][cache_indexes[i]]);
                    }
                }
                if (request->memory_operation == MEMORY_OPERATION_WRITE) this->data_cache[0][cache_indexes[0]].write(request);
            break;
            case MEMORY_OPERATION_INST:
                if (request->next_level != 0 && cache->level == L1) {
                    for (int32_t i = INSTRUCTION_LEVELS - 1; i >= 0; i--) {
                        this->instruction_cache[i+1][cache_indexes[i+1]].returnLine(request, &this->instruction_cache[i][cache_indexes[i]]);
                    }
                }
            break;
            default:
                ERROR_ASSERT_PRINTF (true, "WRONG MEMORY OPERATION TYPE")
            break;
        }
        request->updatePackageWait(ttc);
        request->next_level++;
        cache->cache_hit_per_type[request->memory_operation]++;
        return HIT;
    }
    #if MEMORY_DEBUG
        ORCS_PRINTF (" MISS!\n");
    #endif
    request->updatePackageUntreated(ttc);
    request->next_level++;
    cache->cache_miss_per_type[request->memory_operation]++;
    return MISS;
}
References cache_t::cache_count_per_type, cache_t::cache_hit_per_type, memory_package_t::cache_latency, cache_t::cache_miss_per_type, data_cache, ERROR_ASSERT_PRINTF, get_enum_cache_type_char(), get_enum_memory_operation_char(), orcs_engine_t::get_global_cycle(), HIT, i, cache_t::id, instruction_cache, INSTRUCTION_LEVELS, L1, cache_t::level, memory_package_t::memory_address, memory_package_t::memory_operation, MEMORY_OPERATION_INST, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, MISS, memory_package_t::next_level, orcs_engine, ORCS_PRINTF, requests, cache_t::returnLine(), searchAddress(), memory_package_t::sent_to_cache_level, memory_package_t::sent_to_cache_level_at, memory_package_t::updatePackageUntreated(), memory_package_t::updatePackageWait(), and cache_t::write().
check_cache()
void cache_manager_t::check_cache (uint32_t cache_size, uint32_t cache_level) private
Definition at line 64 of file cache_manager.cpp.
{
    ERROR_ASSERT_PRINTF(utils_t::check_if_power_of_two(cache_size) == OK, "Error - Cache Size Array must be power of 2 value\n")
    if (cache_level == 0) {
        ERROR_ASSERT_PRINTF(NUMBER_OF_PROCESSORS == cache_size, "Error - # First level instruction Caches must be equal # PROCESSORS\n")
    } else {
        ERROR_ASSERT_PRINTF(cache_size <= NUMBER_OF_PROCESSORS,"Error - # Other level instruction Caches must be less or equal # PROCESSORS \n")
    }
}
References utils_t::check_if_power_of_two(), ERROR_ASSERT_PRINTF, NUMBER_OF_PROCESSORS, and OK.
clock()
void cache_manager_t::clock ()
Definition at line 544 of file cache_manager.cpp.
{
    // printf("clock executing\n");
    if (requests.size() > 0) {
        int32_t *cache_indexes = new int32_t[POINTER_LEVELS]();
        for (size_t i = 0; i < requests.size(); i++){
            if (requests[i]->readyAt <= orcs_engine.get_global_cycle()){
                generateIndexArray(requests[i]->processor_id, cache_indexes);
                if (requests[i]->status == PACKAGE_STATE_WAIT){
                    if (requests[i]->sent_to_ram) this->install (requests[i]);
                    this->finishRequest (requests[i], cache_indexes);
                }
                else if (!requests[i]->sent_to_ram) this->process (requests[i], cache_indexes);
            }
        }
        delete[] cache_indexes;
    }
}
References finishRequest(), generateIndexArray(), orcs_engine_t::get_global_cycle(), i, install(), orcs_engine, PACKAGE_STATE_WAIT, POINTER_LEVELS, process(), and requests.
finishRequest()
void cache_manager_t::finishRequest (memory_package_t * request, int32_t * cache_indexes) private
Definition at line 326 of file cache_manager.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[CACM] %lu %lu %s finishes! Took %lu cycles.\n", orcs_engine.get_global_cycle(), request->memory_address, get_enum_memory_operation_char (request->memory_operation), orcs_engine.get_global_cycle()-request->born_cycle)
    #endif
    wait_time = (orcs_engine.get_global_cycle() - request->born_cycle);
    if (request->sent_to_ram && !request->is_hive && !request->is_vima){
        sent_ram++;
        sent_ram_cycles += wait_time;
        if (wait_time > max_sent_ram) max_sent_ram = wait_time;
        if (wait_time < min_sent_ram) min_sent_ram = wait_time;
    } else if (request->is_hive){
        sent_hive++;
        sent_hive_cycles += wait_time;
    } else if (request->is_vima){
        sent_vima++;
        sent_vima_cycles += wait_time;
    }
    this->total_operations[request->memory_operation]++;
    this->total_latency[request->memory_operation] += wait_time;
    if (wait_time < this->min_wait_operations[request->memory_operation]) this->min_wait_operations[request->memory_operation] = wait_time;
    if (wait_time > this->max_wait_operations[request->memory_operation]) this->max_wait_operations[request->memory_operation] = wait_time;
    #if PROCESSOR_DEBUG
        ORCS_PRINTF ("%lu request %s ", orcs_engine.get_global_cycle(), get_enum_memory_operation_char(request->memory_operation))
        if (request->is_vima){
            if (request->vima_read1 != 0) ORCS_PRINTF ("READ1: %lu | ", request->vima_read1)
            if (request->vima_read2 != 0) ORCS_PRINTF ("READ2: %lu | ", request->vima_read2)
            if (request->vima_write != 0) ORCS_PRINTF ("WRITE: %lu | ", request->vima_write)
        } else if (request->is_hive){
            if (request->hive_read1 != 0) ORCS_PRINTF ("READ1: %lu | ", request->hive_read1)
            if (request->hive_read2 != 0) ORCS_PRINTF ("READ2: %lu | ", request->hive_read2)
            if (request->hive_write != 0) ORCS_PRINTF ("WRITE: %lu | ", request->hive_write)
        } else ORCS_PRINTF ("address: %lu ", request->memory_address)
        ORCS_PRINTF ("%lu born at %lu, finished at %lu. Took %lu cycles, came from processor %u.\n", request->uop_number, request->born_cycle, orcs_engine.get_global_cycle(), orcs_engine.get_global_cycle()-request->born_cycle, request->processor_id)
    #endif
    int32_t wait_time_levels = 0;
    if (request->memory_operation == MEMORY_OPERATION_INST) {
        for (i = 0; i < INSTRUCTION_LEVELS; i++) {
            if (request->sent_to_cache_level[this->instruction_cache[i][cache_indexes[i]].level]) {
                #if PROCESSOR_DEBUG
                    ORCS_PRINTF ("%lu memory = %lu | level = %lu, type = %s, count = %u -> count = %u, %s FINISH, %lu\n", orcs_engine.get_global_cycle(), requests.size(), i, get_enum_cache_type_char ((cacheId_t) instruction_cache[i][cache_indexes[i]].id), instruction_cache[i][cache_indexes[i]].count, instruction_cache[i][cache_indexes[i]].count-1, get_enum_memory_operation_char (request->memory_operation), request->memory_address)
                #endif
                wait_time_levels = orcs_engine.get_global_cycle() - request->sent_to_cache_level_at[i];
                this->instruction_cache[i][cache_indexes[i]].count--;
                this->instruction_cache[i][cache_indexes[i]].total_per_type[request->memory_operation] += wait_time_levels;
                if (wait_time_levels > this->instruction_cache[i][cache_indexes[i]].max_per_type[request->memory_operation]) this->instruction_cache[i][cache_indexes[i]].max_per_type[request->memory_operation] = wait_time_levels;
                if (wait_time_levels < this->instruction_cache[i][cache_indexes[i]].min_per_type[request->memory_operation]) this->instruction_cache[i][cache_indexes[i]].min_per_type[request->memory_operation] = wait_time_levels;
                ERROR_ASSERT_PRINTF (this->instruction_cache[i][cache_indexes[i]].count > -1, "VALUE BECOMES NEGATIVE")
            }
        }
        for (i = INSTRUCTION_LEVELS; i < request->next_level; i++) {
            if (request->sent_to_cache_level[this->data_cache[i][cache_indexes[i]].level]) {
                #if PROCESSOR_DEBUG
                    ORCS_PRINTF ("%lu memory = %lu | level = %lu, type = %s, count = %u -> count = %u, %s FINISH, %lu\n", orcs_engine.get_global_cycle(), requests.size(), i, get_enum_cache_type_char ((cacheId_t) data_cache[i][cache_indexes[i]].id), data_cache[i][cache_indexes[i]].count, data_cache[i][cache_indexes[i]].count-1, get_enum_memory_operation_char (request->memory_operation), request->memory_address)
                #endif
                wait_time_levels = orcs_engine.get_global_cycle() - request->sent_to_cache_level_at[i];
                this->data_cache[i][cache_indexes[i]].count--;
                this->data_cache[i][cache_indexes[i]].total_per_type[request->memory_operation] += wait_time_levels;
                if (wait_time_levels > this->data_cache[i][cache_indexes[i]].max_per_type[request->memory_operation]) this->data_cache[i][cache_indexes[i]].max_per_type[request->memory_operation] = wait_time_levels;
                if (wait_time_levels < this->data_cache[i][cache_indexes[i]].min_per_type[request->memory_operation]) this->data_cache[i][cache_indexes[i]].min_per_type[request->memory_operation] = wait_time_levels;
                ERROR_ASSERT_PRINTF (this->data_cache[i][cache_indexes[i]].count > -1, "VALUE BECOMES NEGATIVE")
            }
        }
    } else {
        for (i = 0; i < request->next_level; i++) {
            if (request->sent_to_cache_level[this->data_cache[i][cache_indexes[i]].level]){
                #if PROCESSOR_DEBUG
                    ORCS_PRINTF ("%lu memory = %lu | level = %lu, type = %s, count = %u -> count = %u, %s FINISH, %lu\n", orcs_engine.get_global_cycle(), requests.size(), i, get_enum_cache_type_char ((cacheId_t) data_cache[i][cache_indexes[i]].id), data_cache[i][cache_indexes[i]].count, data_cache[i][cache_indexes[i]].count-1, get_enum_memory_operation_char (request->memory_operation), request->memory_address)
                #endif
                wait_time_levels = orcs_engine.get_global_cycle() - request->sent_to_cache_level_at[i];
                this->data_cache[i][cache_indexes[i]].count--;
                this->data_cache[i][cache_indexes[i]].total_per_type[request->memory_operation] += wait_time_levels;
                if (wait_time_levels > this->data_cache[i][cache_indexes[i]].max_per_type[request->memory_operation]) this->data_cache[i][cache_indexes[i]].max_per_type[request->memory_operation] = wait_time_levels;
                if (wait_time_levels < this->data_cache[i][cache_indexes[i]].min_per_type[request->memory_operation]) this->data_cache[i][cache_indexes[i]].min_per_type[request->memory_operation] = wait_time_levels;
                ERROR_ASSERT_PRINTF (this->data_cache[i][cache_indexes[i]].count > -1, "VALUE BECOMES NEGATIVE")
            }
        }
    }
    //if (request->is_vima) ORCS_PRINTF ("%lu Cache Manager finishRequest(): VIMA INSTRUCTION READY!\n", orcs_engine.get_global_cycle())
    request->updatePackageReady();
    request->updateClients();
    requests.erase (std::remove (requests.begin(), requests.end(), request), requests.end());
    requests.shrink_to_fit();
    //if (request->memory_operation != MEMORY_OPERATION_INST)
    #if PROCESSOR_DEBUG
        ORCS_PRINTF ("%lu Cache Manager finishRequest(): finished memory request %lu from uop %lu, %s.\n", orcs_engine.get_global_cycle(), request->memory_address, request->uop_number, get_enum_memory_operation_char (request->memory_operation))
    #endif
    delete request;
}
References memory_package_t::born_cycle, cache_t::count, data_cache, ERROR_ASSERT_PRINTF, get_enum_cache_type_char(), get_enum_memory_operation_char(), orcs_engine_t::get_global_cycle(), memory_package_t::hive_read1, memory_package_t::hive_read2, memory_package_t::hive_write, i, instruction_cache, INSTRUCTION_LEVELS, memory_package_t::is_hive, memory_package_t::is_vima, cache_t::max_per_type, max_sent_ram, max_wait_operations, memory_package_t::memory_address, memory_package_t::memory_operation, MEMORY_OPERATION_INST, cache_t::min_per_type, min_sent_ram, min_wait_operations, memory_package_t::next_level, orcs_engine, ORCS_PRINTF, memory_package_t::processor_id, requests, sent_hive, sent_hive_cycles, sent_ram, sent_ram_cycles, memory_package_t::sent_to_cache_level, memory_package_t::sent_to_cache_level_at, memory_package_t::sent_to_ram, sent_vima, sent_vima_cycles, total_latency, total_operations, cache_t::total_per_type, memory_package_t::uop_number, memory_package_t::updateClients(), memory_package_t::updatePackageReady(), memory_package_t::vima_read1, memory_package_t::vima_read2, memory_package_t::vima_write, and wait_time.
generateIndexArray()
void cache_manager_t::generateIndexArray (uint32_t processor_id, int32_t * cache_indexes)
Definition at line 248 of file cache_manager.cpp.
{
    for (uint32_t i = 0; i < POINTER_LEVELS; i++) {
        cache_indexes[i] = (int32_t) processor_id & (DCACHE_AMOUNT[i] - 1);
    }
}
References DCACHE_AMOUNT, i, and POINTER_LEVELS.
get_cache_info()
void cache_manager_t::get_cache_info (cacheId_t cache_type, libconfig::Setting & cfg_cache_defs, cache_t * cache, uint32_t cache_level, uint32_t CACHE_AMOUNT) private
Definition at line 122 of file cache_manager.cpp.
{
    const char *string_cache_type;
    if (cache_type == 0) {
        string_cache_type = "INSTRUCTION";
    } else {
        string_cache_type = "DATA";
    }
    libconfig::Setting &cfg_caches = cfg_cache_defs[string_cache_type];
    // Get information of each cache
    for (uint32_t j = 0; j < CACHE_AMOUNT; j ++) {
        for (int32_t i = 0; i < cfg_caches.getLength(); i++) {
            try {
                libconfig::Setting &cfg_cache = cfg_caches[i];
                if ((uint32_t)cfg_cache["LEVEL"] == cache_level) {
                    cache[j].id = cache_type;
                    cache[j].size = cfg_cache["SIZE"];
                    cache[j].level = cfg_cache["LEVEL"];
                    cache[j].offset = utils_t::get_power_of_two(LINE_SIZE);
                    cache[j].latency = cfg_cache["LATENCY"];
                    cache[j].associativity = cfg_cache["ASSOCIATIVITY"];
                    cache[j].mshr_size = cfg_cache["MSHR_SIZE"];
                    cache[j].n_sets = (cache[j].size / LINE_SIZE) / cache[j].associativity;
                    cache[j].set_LINE_SIZE (LINE_SIZE);
                }
            } catch (libconfig::SettingNotFoundException const &nfex) {
                ERROR_PRINTF("MISSING CACHE PARAMETERS");
            } catch (libconfig::SettingTypeException const &tex) {
                ERROR_PRINTF("WRONG TYPE CACHE PARAMETERS");
            }
        }
    }
}
References cache_t::associativity, ERROR_PRINTF, utils_t::get_power_of_two(), i, cache_t::id, cache_t::latency, cache_t::level, LINE_SIZE, cache_t::mshr_size, cache_t::n_sets, cache_t::offset, and cache_t::size.
get_cache_levels()
void cache_manager_t::get_cache_levels (cacheId_t cache_type, libconfig::Setting & cfg_cache_defs) private
Definition at line 73 of file cache_manager.cpp.
{
    const char *string_cache_type;
    if (cache_type == 0) {
        string_cache_type = "INSTRUCTION";
    } else {
        string_cache_type = "DATA";
    }
    vector<uint32_t> clevels, camount;
    libconfig::Setting &cfg_caches = cfg_cache_defs[string_cache_type];
    uint32_t N_CACHES = cfg_caches.getLength();
    for (uint32_t i = 0; i < N_CACHES; i++) {
        try {
            libconfig::Setting &cfg_cache = cfg_caches[i];
            clevels.push_back(cfg_cache["LEVEL"]);
        } catch (libconfig::SettingNotFoundException const &nfex) {
            ERROR_PRINTF("MISSING CACHE PARAMETERS");
        } catch (libconfig::SettingTypeException const &tex) {
            ERROR_PRINTF("WRONG TYPE CACHE PARAMETERS");
        }
    }
    camount = clevels;
    std::sort(clevels.begin(), clevels.end());
    clevels.erase(std::unique(clevels.begin(), clevels.end()), clevels.end());
    clevels.shrink_to_fit();
//TODO CHECK DCACHE_AMOUNT masks.
    if (cache_type == 0) {
        set_INSTRUCTION_LEVELS(clevels.size());
        ICACHE_AMOUNT = new uint32_t[INSTRUCTION_LEVELS]();
        for (uint32_t i = 0; i < INSTRUCTION_LEVELS; i++) {
            ICACHE_AMOUNT[i] = std::count(camount.begin(), camount.end(), i);
        }
    } else {
        set_DATA_LEVELS(clevels.size());
        DCACHE_AMOUNT = new uint32_t[DATA_LEVELS]();
        for (uint32_t i = 0; i < DATA_LEVELS; i++) {
            DCACHE_AMOUNT[i] = std::count(camount.begin(), camount.end(), i);
        }
        //POINTER_LEVELS = 3;
        POINTER_LEVELS = ((INSTRUCTION_LEVELS > DATA_LEVELS) ? INSTRUCTION_LEVELS : DATA_LEVELS);
    }
    //valgrind accused memory leak even when using delete, swapping actually solved the issue to erase these vectors.
    std::vector<uint32_t>().swap(clevels);
    std::vector<uint32_t>().swap(camount);
}
References DATA_LEVELS, DCACHE_AMOUNT, ERROR_PRINTF, i, ICACHE_AMOUNT, INSTRUCTION_LEVELS, and POINTER_LEVELS.
install()
void cache_manager_t::install (memory_package_t * request) private
Definition at line 422 of file cache_manager.cpp.
{
    #if PROCESSOR_DEBUG
        printf("%lu Cache Manager installCache(): %lu in processor %u\n", orcs_engine.get_global_cycle(), request->memory_address, request->processor_id);
    #endif
    int32_t *cache_indexes = new int32_t[POINTER_LEVELS]();
    this->generateIndexArray(request->processor_id, cache_indexes);
    switch (request->memory_operation){
        case MEMORY_OPERATION_INST:{
            // printf("instruction");
            this->installCacheLines(request, cache_indexes, 0, INSTRUCTION);
            break;
        }
        case MEMORY_OPERATION_READ:{
            // printf("read");
            this->installCacheLines(request, cache_indexes, 0, DATA);
            break;
        }
        case MEMORY_OPERATION_WRITE:{
            // printf("write");
            this->installCacheLines(request, cache_indexes, 0, DATA);
            int cache_level = DATA_LEVELS - 1;
            for (int32_t k = cache_level - 1; k >= 0; k--) {
                this->data_cache[k+1][cache_indexes[k+1]].add_cache_write();
            }
            this->data_cache[0][cache_indexes[0]].write(request);
            break;
        }
        default:
            break;
    }
    delete[] cache_indexes;
}
References DATA, data_cache, DATA_LEVELS, generateIndexArray(), orcs_engine_t::get_global_cycle(), installCacheLines(), INSTRUCTION, memory_package_t::memory_address, memory_package_t::memory_operation, MEMORY_OPERATION_INST, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, orcs_engine, POINTER_LEVELS, memory_package_t::processor_id, and cache_t::write().
installCacheLines()
void cache_manager_t::installCacheLines (memory_package_t * request, int32_t * cache_indexes, uint32_t latency_request, cacheId_t cache_type) private
Definition at line 255 of file cache_manager.cpp.
{
    // printf("installCacheLines %lu in processor %u\n", request->memory_address, request->processor_id);
    uint32_t i, j;
    uint64_t llc_idx, llc_line;
    uint64_t *CACHE_TAGS = new uint64_t[POINTER_LEVELS]();
    line_t ***line = new line_t**[NUMBER_OF_PROCESSORS]();
    for (i = 0; i < NUMBER_OF_PROCESSORS; i++) {
        line[i] = new line_t*[POINTER_LEVELS]();
        for (j = 0; j < POINTER_LEVELS; j++) {
            line[i][j] = NULL;
        }
    }
    if (cache_type == INSTRUCTION) {
        for (i = 0; i < INSTRUCTION_LEVELS; i++) {
            // printf("cache[%d][%d]\n", i, cache_indexes[i]);
            line[request->processor_id][i] = this->instruction_cache[i][cache_indexes[i]].installLine(request, latency_request, llc_idx, llc_line);
            //ORCS_PRINTF ("INST Installed addr: %lu, level: %u ", instructionAddress, i)
            //this->instruction_cache[i][cache_indexes[i]].printTagIdx (instructionAddress);
        }
    } else {
        i = 0;
    }
    for (; i < POINTER_LEVELS; i++) {
        // printf("cache[%d][%d]\n", i, cache_indexes[i]);
        line[request->processor_id][i] = this->data_cache[i][cache_indexes[i]].installLine(request, latency_request, llc_idx, llc_line);
        //ORCS_PRINTF ("DATA Installed addr: %lu, level: %u ", instructionAddress, i)
        //this->data_cache[i][cache_indexes[i]].printTagIdx (instructionAddress);
    }
    for (i = 0; i < POINTER_LEVELS; i++) {
        for (j = 0; j < POINTER_LEVELS; j++) {
            if (i == j) {
                continue;
            }
            line[request->processor_id][i]->line_ptr_caches[request->processor_id][j] = line[request->processor_id][j];
        }
    }
    for (i = 0; i < NUMBER_OF_PROCESSORS; i++) {
        for (j = 0; j < POINTER_LEVELS; j++) {
            line[i][j] = NULL;
        }
    }
    for (i = 0; i < NUMBER_OF_PROCESSORS; i++) delete[] line[i];
    delete[] line;
    delete[] CACHE_TAGS;
}
References data_cache, i, cache_t::installLine(), INSTRUCTION, instruction_cache, INSTRUCTION_LEVELS, line_t::line_ptr_caches, NUMBER_OF_PROCESSORS, POINTER_LEVELS, and memory_package_t::processor_id.
instantiate_cache()
cache_t ** cache_manager_t::instantiate_cache (cacheId_t cache_type, libconfig::Setting & cfg_cache_defs) private
Definition at line 158 of file cache_manager.cpp.
{
    this->get_cache_levels(cache_type, cfg_cache_defs);
    uint32_t CACHE_LEVELS, *CACHE_AMOUNT = NULL;
    if (cache_type == INSTRUCTION) {
        set_INSTRUCTION_LEVELS(INSTRUCTION_LEVELS);
        CACHE_LEVELS = INSTRUCTION_LEVELS;
        CACHE_AMOUNT = new uint32_t[CACHE_LEVELS]();
        for (uint32_t i = 0; i < CACHE_LEVELS; i++) {
            CACHE_AMOUNT[i] = ICACHE_AMOUNT[i];
            //ORCS_PRINTF ("ICACHE_AMOUNT[%u] = %u\n", i, ICACHE_AMOUNT[i])
        }
    } else {
        set_DATA_LEVELS(DATA_LEVELS);
        CACHE_LEVELS = DATA_LEVELS;
        CACHE_AMOUNT = new uint32_t[CACHE_LEVELS]();
        for (uint32_t i = 0; i < CACHE_LEVELS; i++) {
            CACHE_AMOUNT[i] = DCACHE_AMOUNT[i];
            //ORCS_PRINTF ("DCACHE_AMOUNT[%u] = %u\n", i, ICACHE_AMOUNT[i])
        }
    }
    // ORCS_PRINTF ("CACHE_LEVELS = %u\n", CACHE_LEVELS)
    cache_t **cache = new cache_t *[CACHE_LEVELS]();
    for (uint32_t i = 0; i < CACHE_LEVELS; i++) {
        cache[i] = new cache_t[CACHE_AMOUNT[i]]();
        this->get_cache_info(cache_type, cfg_cache_defs, cache[i], i, CACHE_AMOUNT[i]);
        this->check_cache(CACHE_AMOUNT[i], i);
        for (uint32_t j = 0; j < CACHE_AMOUNT[i]; j++) {
            cache[i][j].allocate(NUMBER_OF_PROCESSORS, INSTRUCTION_LEVELS, DATA_LEVELS);
        }
    }
    delete[] CACHE_AMOUNT;
    return cache;
}
References cache_t::allocate(), check_cache(), DATA_LEVELS, DCACHE_AMOUNT, get_cache_info(), get_cache_levels(), i, ICACHE_AMOUNT, INSTRUCTION, INSTRUCTION_LEVELS, and NUMBER_OF_PROCESSORS.
isIn()
bool cache_manager_t::isIn (memory_package_t * mob_line) private
Definition at line 302 of file cache_manager.cpp.
{
    if (request->is_hive || request->is_vima) return false;
    uint64_t tag = (request->memory_address >> this->offset);
    //ORCS_PRINTF ("%lu %s\n", tag, get_enum_memory_operation_char (request->memory_operation))
    for (i = 0; i < requests.size(); i++){
        if ((requests[i]->memory_address >> this->offset) == tag && requests[i]->type == request->type) {
            #if MEMORY_DEBUG
                ORCS_PRINTF ("will be forwarded by %lu %s.\n", requests[i]->memory_address, get_enum_memory_operation_char (requests[i]->memory_operation))
            #endif
            for (size_t j = 0; j < request->clients.size(); j++) requests[i]->clients.push_back (request->clients[j]);
            delete request;
            return true;
        }
    }
    return false;
}
References memory_package_t::clients, get_enum_memory_operation_char(), i, memory_package_t::is_hive, memory_package_t::is_vima, memory_package_t::memory_address, offset, ORCS_PRINTF, requests, and memory_package_t::type.
print_requests()
void cache_manager_t::print_requests () private
Definition at line 319 of file cache_manager.cpp.
{
    ORCS_PRINTF ("-------------%lu------------\n", orcs_engine.get_global_cycle())
    for (size_t i = 0; i < requests.size(); i++){
        ORCS_PRINTF ("MSHR Table entry %lu: mop %s | uop %lu | status %s.\n", i, get_enum_memory_operation_char (requests[i]->memory_operation), requests[i]->uop_number, get_enum_package_state_char (requests[i]->status))
    }
}
References get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), i, orcs_engine, ORCS_PRINTF, and requests.
process()
void cache_manager_t::process (memory_package_t * request, int32_t * cache) private
Definition at line 473 of file cache_manager.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[CACM] %lu %lu %s will now be processed |", orcs_engine.get_global_cycle(), request->memory_address, get_enum_memory_operation_char (request->memory_operation))
    #endif
    #if PROCESSOR_DEBUG
        ORCS_PRINTF ("%lu Cache Manager process(): request %lu, %s %s, readyAt %lu \n", orcs_engine.get_global_cycle(), request->memory_address, get_enum_memory_operation_char (request->memory_operation), get_enum_package_state_char (request->status), request->readyAt)
    #endif
    cache_t* cache;
    switch (request->memory_operation){
        case MEMORY_OPERATION_READ:
        case MEMORY_OPERATION_WRITE:
        case MEMORY_OPERATION_INST:
            if (request->next_level < DATA_LEVELS){
                if (request->status == PACKAGE_STATE_UNTREATED && request->readyAt <= orcs_engine.get_global_cycle()){
                    if (request->memory_operation == MEMORY_OPERATION_INST && request->next_level == L1) {
                        cache = &this->instruction_cache[request->next_level][cache_indexes[request->next_level]];
                    } else cache = &this->data_cache[request->next_level][cache_indexes[request->next_level]];
                    if (cache->count < cache->mshr_size) {
                        #if MEMORY_DEBUG
                            ORCS_PRINTF (" sent to %s |", get_enum_cache_level_char ((cacheLevel_t) request->next_level))
                        #endif
                        /*if (request->memory_operation == MEMORY_OPERATION_WRITE && request->memory_size == this->get_LINE_SIZE()){
                            request->updatePackageWait(this->data_cache[request->next_level][cache_indexes[request->processor_id]].latency);
                            request->sent_to_ram = true;
                        }
                        else */
                        this->cache_search (request, cache, cache_indexes);
                    }
                }
            } else if (!request->sent_to_ram) {
                #if MEMORY_DEBUG
                    ORCS_PRINTF (" sent to RAM.\n")
                #endif
                orcs_engine.memory_controller->add_requests_llc();
                orcs_engine.memory_controller->requestDRAM (request);
            }
            break;
        case MEMORY_OPERATION_HIVE_FP_ALU:
        case MEMORY_OPERATION_HIVE_FP_DIV:
        case MEMORY_OPERATION_HIVE_FP_MUL:
        case MEMORY_OPERATION_HIVE_INT_ALU:
        case MEMORY_OPERATION_HIVE_INT_DIV:
        case MEMORY_OPERATION_HIVE_INT_MUL:
        case MEMORY_OPERATION_HIVE_LOAD:
        case MEMORY_OPERATION_HIVE_STORE:
        case MEMORY_OPERATION_HIVE_LOCK:
        case MEMORY_OPERATION_HIVE_UNLOCK:
            #if MEMORY_DEBUG
                ORCS_PRINTF (" sent to HIVE Controller.\n")
            #endif
            orcs_engine.hive_controller->addRequest (request);
            break;
        case MEMORY_OPERATION_VIMA_FP_ALU:
        case MEMORY_OPERATION_VIMA_FP_MUL:
        case MEMORY_OPERATION_VIMA_FP_DIV:
        case MEMORY_OPERATION_VIMA_INT_ALU:
        case MEMORY_OPERATION_VIMA_INT_MUL:
        case MEMORY_OPERATION_VIMA_INT_DIV:
        case MEMORY_OPERATION_VIMA_INT_MLA:
        case MEMORY_OPERATION_VIMA_FP_MLA:
            #if MEMORY_DEBUG
                ORCS_PRINTF (" sent to VIMA Controller.\n")
            #endif
            orcs_engine.vima_controller->addRequest (request);
            break;
        default:
            ERROR_ASSERT_PRINTF (true, "WRONG MEMORY OPERATION TYPE")
            break;
    }
}
References hive_controller_t::addRequest(), vima_controller_t::addRequest(), cache_search(), data_cache, DATA_LEVELS, ERROR_ASSERT_PRINTF, get_enum_cache_level_char(), get_enum_memory_operation_char(), get_enum_package_state_char(), orcs_engine_t::get_global_cycle(), orcs_engine_t::hive_controller, instruction_cache, L1, memory_package_t::memory_address, orcs_engine_t::memory_controller, memory_package_t::memory_operation, MEMORY_OPERATION_HIVE_FP_ALU, MEMORY_OPERATION_HIVE_FP_DIV, MEMORY_OPERATION_HIVE_FP_MUL, MEMORY_OPERATION_HIVE_INT_ALU, MEMORY_OPERATION_HIVE_INT_DIV, MEMORY_OPERATION_HIVE_INT_MUL, MEMORY_OPERATION_HIVE_LOAD, MEMORY_OPERATION_HIVE_LOCK, MEMORY_OPERATION_HIVE_STORE, MEMORY_OPERATION_HIVE_UNLOCK, MEMORY_OPERATION_INST, MEMORY_OPERATION_READ, MEMORY_OPERATION_VIMA_FP_ALU, MEMORY_OPERATION_VIMA_FP_DIV, MEMORY_OPERATION_VIMA_FP_MLA, MEMORY_OPERATION_VIMA_FP_MUL, MEMORY_OPERATION_VIMA_INT_ALU, MEMORY_OPERATION_VIMA_INT_DIV, MEMORY_OPERATION_VIMA_INT_MLA, MEMORY_OPERATION_VIMA_INT_MUL, MEMORY_OPERATION_WRITE, memory_package_t::next_level, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_UNTREATED, memory_package_t::readyAt, memory_controller_t::requestDRAM(), memory_package_t::sent_to_ram, memory_package_t::status, and orcs_engine_t::vima_controller.
searchAddress()
uint32_t cache_manager_t::searchAddress (uint64_t instructionAddress, cache_t * cache, uint32_t * latency_request, uint32_t * ttc) private
Definition at line 562 of file cache_manager.cpp.
{
    uint32_t cache_status = cache->read(instructionAddress, *ttc);
    *latency_request += *ttc;
    return cache_status;
}
References cache_t::read().
searchData()
bool cache_manager_t::searchData (memory_package_t * mob_line)
Definition at line 456 of file cache_manager.cpp.
{
    #if MEMORY_DEBUG
        ORCS_PRINTF ("[CACM] %lu %lu %s enters | ", orcs_engine.get_global_cycle(), request->memory_address, get_enum_memory_operation_char (request->memory_operation))
    #endif
    if (request->memory_operation == MEMORY_OPERATION_READ) this->add_reads();
    else if (request->memory_operation == MEMORY_OPERATION_WRITE) this->add_writes();
    if (!isIn (request)) {
        requests.push_back (request);
        requests.shrink_to_fit();
        #if MEMORY_DEBUG
            ORCS_PRINTF ("is new.\n")
        #endif
    }
    return true;
}
References get_enum_memory_operation_char(), orcs_engine_t::get_global_cycle(), isIn(), memory_package_t::memory_address, memory_package_t::memory_operation, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, orcs_engine, ORCS_PRINTF, and requests.
statistics()
void cache_manager_t::statistics (uint32_t core_id)
Definition at line 638 of file cache_manager.cpp.
{
    int32_t *cache_indexes = new int32_t[POINTER_LEVELS]();
    bool close = false;
    FILE *output = stdout;
    if (orcs_engine.output_file_name != NULL) {
        output = fopen(orcs_engine.output_file_name,"a+");
        close=true;
    }
    if (output != NULL) {
        utils_t::largestSeparator(output);
        fprintf(output,"#========================================================================#\n");
        fprintf(output,"#Cache Manager\n");
        fprintf(output,"#========================================================================#\n");
        if (this->get_sent_ram() > 0) {
            ORCS_PRINTF ("Total Reads:                       %lu\nTotal Writes:                      %lu\n", this->get_reads(), this->get_writes())
            ORCS_PRINTF ("Total RAM requests:                %lu\nTotal RAM request latency cycles:  %lu\n", this->get_sent_ram(), this->get_sent_ram_cycles())
            ORCS_PRINTF ("Avg. wait for RAM requests:        %lu\n", sent_ram_cycles/sent_ram)
            ORCS_PRINTF ("Min. wait for RAM requests:        %lu\n", min_sent_ram)
            ORCS_PRINTF ("Max. wait for RAM requests:        %lu\n", max_sent_ram)
        }
        if (this->get_sent_hive() > 0) {
            ORCS_PRINTF ("Total HIVE requests:               %lu\nTotal HIVE request latency cycles: %lu\n", this->get_sent_hive(), this->get_sent_hive_cycles())
            ORCS_PRINTF ("Average wait for HIVE requests:    %lu\n", sent_hive_cycles/sent_hive)
        }
        if (this->get_sent_vima() > 0){
            ORCS_PRINTF ("Total VIMA requests:               %lu\nTotal VIMA request latency cycles: %lu\n", this->get_sent_vima(), this->get_sent_vima_cycles())
            ORCS_PRINTF ("Average wait for VIMA requests:    %lu\n", sent_vima_cycles/sent_vima)
        }
        utils_t::largestSeparator(output);
        for (i = 0; i < MEMORY_OPERATION_LAST; i++){
            if (this->total_operations[i] > 0) {
                fprintf(output,"%s_Tot._Latency_Hierarchy:  %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->total_latency[i]);
                fprintf(output,"%s_Avg._Latency_Hierarchy:  %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->total_latency[i]/this->total_operations[i]);
            }
            if (this->min_wait_operations[i] < UINT64_MAX) fprintf(output,"%s_Min._Latency_Hierarchy:  %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->min_wait_operations[i]);
            if (this->max_wait_operations[i] > 0) fprintf(output,"%s_Max._Latency_Hierarchy:  %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->max_wait_operations[i]);
        }
    }
    if(close) fclose(output);
    this->generateIndexArray(core_id, cache_indexes);
    for (uint32_t i = 0; i < INSTRUCTION_LEVELS; i++) {
        this->instruction_cache[i][cache_indexes[i]].statistics();
    }
    for (uint32_t i = 0; i < DATA_LEVELS; i++) {
        this->data_cache[i][cache_indexes[i]].statistics();
    }
    // Prefetcher
    if (PREFETCHER_ACTIVE){
        this->prefetcher->statistics();
    }
    delete[] cache_indexes;
}
References data_cache, DATA_LEVELS, generateIndexArray(), get_enum_memory_operation_char(), i, instruction_cache, INSTRUCTION_LEVELS, utils_t::largestSeparator(), max_sent_ram, max_wait_operations, MEMORY_OPERATION_LAST, min_sent_ram, min_wait_operations, orcs_engine, ORCS_PRINTF, orcs_engine_t::output_file_name, POINTER_LEVELS, prefetcher, PREFETCHER_ACTIVE, sent_hive, sent_hive_cycles, sent_ram, sent_ram_cycles, sent_vima, sent_vima_cycles, cache_t::statistics(), prefetcher_t::statistics(), total_latency, and total_operations.
The documentation for this class was generated from the following files:
cache/cache_manager.hpp
cache/cache_manager.cpp