OrCS: memory_request_client_t Class Reference
memory_request_client_t Class Reference
#include <memory_request_client.hpp>
Public Member Functions
memory_request_client_t ()
virtual ~memory_request_client_t ()
virtual void updatePackageUntreated (uint32_t stallTime)
virtual void updatePackageReady (uint32_t stallTime)
virtual void updatePackageWait (uint32_t stallTime)
virtual void updatePackageFree (uint32_t stallTime)
Public Attributes
package_state_t status
uint32_t readyAt
memory_operation_t memory_operation
bool waiting_DRAM
Detailed Description
Definition at line 3 of file memory_request_client.hpp.
Constructor & Destructor Documentation
memory_request_client_t()
memory_request_client_t::memory_request_client_t ()
Definition at line 7 of file memory_request_client.cpp.
{
}
~memory_request_client_t()
memory_request_client_t::~memory_request_client_t () virtual
Definition at line 11 of file memory_request_client.cpp.
{
}
Member Function Documentation
updatePackageFree()
void memory_request_client_t::updatePackageFree (uint32_t stallTime) virtual
Definition at line 31 of file memory_request_client.cpp.
{
    this->status = PACKAGE_STATE_FREE;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_FREE, readyAt, and status.
updatePackageReady()
void memory_request_client_t::updatePackageReady (uint32_t stallTime) virtual
Definition at line 21 of file memory_request_client.cpp.
{
    this->status = PACKAGE_STATE_READY;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_READY, readyAt, and status.
updatePackageUntreated()
void memory_request_client_t::updatePackageUntreated (uint32_t stallTime) virtual
Definition at line 16 of file memory_request_client.cpp.
{
    this->status = PACKAGE_STATE_UNTREATED;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_UNTREATED, readyAt, and status.
updatePackageWait()
void memory_request_client_t::updatePackageWait (uint32_t stallTime) virtual
Definition at line 26 of file memory_request_client.cpp.
{
    this->status = PACKAGE_STATE_WAIT;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_WAIT, readyAt, and status.
The documentation for this class was generated from the following files:
main_memory/memory_request_client.hpp
main_memory/memory_request_client.cpp