OrCS: uop_package_t Class Reference
uop_package_t Class Reference
#include <uop_package.hpp>
Public Member Functions
uop_package_t ()
~uop_package_t ()
void opcode_to_uop (uint64_t uop_number, instruction_operation_t uop_operation, uint64_t memory_address, uint32_t memory_size, opcode_package_t opcode)
bool operator== (const uop_package_t &package)
void package_clean ()
void updatePackageUntrated (uint32_t stallTime)
void updatePackageReady (uint32_t stallTime)
void updatePackageWait (uint32_t stallTime)
void updatePackageFree (uint32_t stallTime)
std::string content_to_string ()
Convert Instruction variables into String.
std::string content_to_string2 ()
Convert Instruction variables into String.
Public Attributes
char opcode_assembly [MAX_ASSEMBLY_SIZE]
TRACE Variables.
instruction_operation_t opcode_operation
uint64_t opcode_address
uint32_t opcode_size
int32_t read_regs [MAX_REGISTERS]
int32_t write_regs [MAX_REGISTERS]
instruction_operation_t uop_operation
uint64_t memory_address
uint32_t memory_size
uint64_t read_address
uint64_t read2_address
uint64_t write_address
bool is_hive
int32_t hive_read1
int32_t hive_read2
int32_t hive_write
bool is_vima
uint64_t opcode_number
uint64_t uop_number
uint64_t born_cycle
uint64_t readyAt
package_state_t status
Detailed Description
Definition at line 1 of file uop_package.hpp.
Constructor & Destructor Documentation
uop_package_t()
uop_package_t::uop_package_t ()
Definition at line 3 of file uop_package.cpp.
{}
~uop_package_t()
uop_package_t::~uop_package_t ()
Definition at line 5 of file uop_package.cpp.
{}
Member Function Documentation
content_to_string()
std::string uop_package_t::content_to_string ()
Convert Instruction variables into String.
Definition at line 93 of file uop_package.cpp.
{
    std::string content_string;
    content_string = "";
    content_string = content_string + "Uop Number " + utils_t::uint64_to_string(this->uop_number);
    content_string = content_string + " " + utils_t::uint64_to_string(this->opcode_address);
    content_string = content_string + " " + get_enum_instruction_operation_char(this->uop_operation);
    content_string = content_string + " Address $" + utils_t::big_uint64_to_string(this->memory_address);
    content_string = content_string + " Size:" + utils_t::uint32_to_string(this->memory_size);
    content_string = content_string + " | RRegs[";
    for (uint32_t i = 0; i < MAX_REGISTERS; i++) {
        if (this->read_regs[i] >= 0) {
            content_string = content_string + " " + utils_t::uint32_to_string(this->read_regs[i]);
        }
    }
    content_string = content_string + " ] | WRegs[";
    for (uint32_t i = 0; i < MAX_REGISTERS; i++) {
        if (this->write_regs[i] >= 0) {
            content_string = content_string + " " + utils_t::uint32_to_string(this->write_regs[i]);
        }
    }
    content_string = content_string + " ]";
    return content_string;
}
References utils_t::big_uint64_to_string(), get_enum_instruction_operation_char(), MAX_REGISTERS, memory_address, memory_size, opcode_address, read_regs, utils_t::uint32_to_string(), utils_t::uint64_to_string(), uop_number, uop_operation, and write_regs.
content_to_string2()
std::string uop_package_t::content_to_string2 ()
Convert Instruction variables into String.
Definition at line 124 of file uop_package.cpp.
{
    std::string content_string;
    content_string = "";
    content_string = content_string + " " + utils_t::uint64_to_string(this->opcode_address);
    content_string = content_string + " " + get_enum_instruction_operation_char(this->uop_operation);
    content_string = content_string + " Status Opcode "+ get_enum_package_state_char(this->status);
    content_string = content_string + " Ready At" + utils_t::uint64_to_string(this->readyAt);
    return content_string;
}
References get_enum_instruction_operation_char(), get_enum_package_state_char(), opcode_address, readyAt, status, utils_t::uint64_to_string(), and uop_operation.
opcode_to_uop()
void uop_package_t::opcode_to_uop (uint64_t uop_number, instruction_operation_t uop_operation, uint64_t memory_address, uint32_t memory_size, opcode_package_t opcode)
TRACE Variables
Definition at line 56 of file uop_package.cpp.
{
    // ERROR_ASSERT_PRINTF(this->state == PACKAGE_STATE_FREE,
    //                     "Trying to decode to uop in a non-free location\n");
    this->uop_number = uop_number;
    strncpy(this->opcode_assembly, opcode.opcode_assembly, sizeof(this->opcode_assembly));
    this->opcode_operation = opcode.opcode_operation;
    this->opcode_address = opcode.opcode_address;
    this->opcode_size = opcode.opcode_size;
    this->opcode_number = opcode.opcode_number;
    memcpy(this->read_regs, opcode.read_regs, sizeof(int32_t) * MAX_REGISTERS);
    memcpy(this->write_regs, opcode.write_regs, sizeof(int32_t) * MAX_REGISTERS);
    this->uop_operation = uop_operation;
    this->memory_address = memory_address;
    this->memory_size = memory_size;
}
References MAX_REGISTERS, memory_address, memory_size, opcode_package_t::opcode_address, opcode_address, opcode_package_t::opcode_assembly, opcode_assembly, opcode_package_t::opcode_number, opcode_number, opcode_package_t::opcode_operation, opcode_operation, opcode_package_t::opcode_size, opcode_size, opcode_package_t::read_regs, read_regs, uop_number, uop_operation, opcode_package_t::write_regs, and write_regs.
operator==()
bool uop_package_t::operator== (const uop_package_t & package)
TRACE Variables
Definition at line 34 of file uop_package.cpp.
{
    if (strcmp(this->opcode_assembly, package.opcode_assembly) != 0) return FAIL;
    if (this->opcode_operation != package.opcode_operation) return FAIL;
    if (this->opcode_address != package.opcode_address) return FAIL;
    if (this->opcode_size != package.opcode_size) return FAIL;
    if ( memcmp(this->read_regs, package.read_regs, sizeof(int32_t)*MAX_REGISTERS) != 0) return FAIL;
    if ( memcmp(this->write_regs, package.write_regs, sizeof(int32_t)*MAX_REGISTERS) != 0) return FAIL;
    if (this->uop_operation != package.uop_operation) return FAIL;
    if (this->memory_address != package.memory_address) return FAIL;
    if (this->memory_size != package.memory_size) return FAIL;
    if (this->opcode_number != package.opcode_number) return FAIL;
    if (this->uop_number != package.uop_number) return FAIL;
    if (this->readyAt != package.readyAt) return FAIL;
    if (this->status != package.status) return FAIL;
    return OK;
}
References FAIL, MAX_REGISTERS, memory_address, memory_size, OK, opcode_address, opcode_assembly, opcode_number, opcode_operation, opcode_size, read_regs, readyAt, status, uop_number, uop_operation, and write_regs.
package_clean()
void uop_package_t::package_clean ()
TRACE Variables
Definition at line 6 of file uop_package.cpp.
{
    strcpy(this->opcode_assembly, "N/A");
    this->opcode_operation = INSTRUCTION_OPERATION_NOP;
    this->opcode_address = 0;
    this->opcode_size = 0;
    this->is_hive = false;
    this->hive_read1 = -1;
    this->hive_read2 = -1;
    this->hive_write = -1;
    this->is_vima = false;
    memset(this->read_regs, POSITION_FAIL, sizeof(int32_t) * MAX_REGISTERS);
    memset(this->write_regs, POSITION_FAIL, sizeof(int32_t) * MAX_REGISTERS);
    this->uop_operation = INSTRUCTION_OPERATION_NOP;
    this->memory_address = 0;
    this->memory_size = 0;
    //controle
    this->opcode_number = 0;
    this->uop_number = 0;
    this->born_cycle = 0;
    this->readyAt = orcs_engine.get_global_cycle();
    this->status =PACKAGE_STATE_FREE;
}
References born_cycle, orcs_engine_t::get_global_cycle(), hive_read1, hive_read2, hive_write, INSTRUCTION_OPERATION_NOP, is_hive, is_vima, MAX_REGISTERS, memory_address, memory_size, opcode_address, opcode_assembly, opcode_number, opcode_operation, opcode_size, orcs_engine, PACKAGE_STATE_FREE, POSITION_FAIL, read_regs, readyAt, status, uop_number, uop_operation, and write_regs.
updatePackageFree()
void uop_package_t::updatePackageFree (uint32_t stallTime)
Definition at line 88 of file uop_package.cpp.
{
    this->status = PACKAGE_STATE_FREE;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_FREE, readyAt, and status.
updatePackageReady()
void uop_package_t::updatePackageReady (uint32_t stallTime)
Definition at line 80 of file uop_package.cpp.
{
    this->status = PACKAGE_STATE_READY;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_READY, readyAt, and status.
updatePackageUntrated()
void uop_package_t::updatePackageUntrated (uint32_t stallTime)
Definition at line 76 of file uop_package.cpp.
{
    this->status = PACKAGE_STATE_UNTREATED;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_UNTREATED, readyAt, and status.
updatePackageWait()
void uop_package_t::updatePackageWait (uint32_t stallTime)
Definition at line 84 of file uop_package.cpp.
{
    this->status = PACKAGE_STATE_WAIT;
    this->readyAt = orcs_engine.get_global_cycle()+stallTime;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, PACKAGE_STATE_WAIT, readyAt, and status.
The documentation for this class was generated from the following files:
package/uop_package.hpp
package/uop_package.cpp