OrCS: disambiguation_hashed_t Class Reference
disambiguation_hashed_t Class Reference
#include <disambiguation_hashed.hpp>
Public Member Functions
disambiguation_hashed_t ()
~disambiguation_hashed_t ()
void allocate ()
void make_memory_dependences (memory_order_buffer_line_t *mob_line)
void solve_memory_dependences (memory_order_buffer_line_t *mob_line)
void statistics ()
Public Member Functions inherited from desambiguation_t
virtual ~desambiguation_t ()
Public Attributes
memory_order_buffer_line_t ** disambiguation_load_hash
uint32_t disambiguation_load_hash_bits_shift
uint32_t disambiguation_load_hash_bits_mask
memory_order_buffer_line_t ** disambiguation_store_hash
uint32_t disambiguation_store_hash_bits_shift
uint32_t disambiguation_store_hash_bits_mask
uint64_t stat_disambiguation_read_false_positive
uint64_t stat_disambiguation_write_false_positive
uint64_t stat_address_to_address
Private Attributes
uint32_t ROB_SIZE
uint32_t LOAD_HASH_SIZE
uint32_t STORE_HASH_SIZE
uint32_t DESAMBIGUATION_BLOCK_SIZE
uint32_t ADDRESS_TO_ADDRESS
uint32_t REGISTER_FORWARD
uint32_t WAIT_CYCLE
Detailed Description
Definition at line 2 of file disambiguation_hashed.hpp.
Constructor & Destructor Documentation
disambiguation_hashed_t()
disambiguation_hashed_t::disambiguation_hashed_t ()
Definition at line 3 of file disambiguation_hashed.cpp.
{
    this->ROB_SIZE = 0;
    this->LOAD_HASH_SIZE = 0;
    this->STORE_HASH_SIZE = 0;
    this->DESAMBIGUATION_BLOCK_SIZE = 0;
    this->ADDRESS_TO_ADDRESS = 0;
    this->REGISTER_FORWARD = 0;
    this->WAIT_CYCLE = 0;
    // HASHED LOAD/STORE
    this->disambiguation_load_hash = NULL;
    this->disambiguation_store_hash = NULL;
    // LOAD/STORE Hash mask
    this->disambiguation_load_hash_bits_mask = 0;
    this->disambiguation_store_hash_bits_mask = 0;
    // LOAD/STORE Hash shift
    this->disambiguation_load_hash_bits_shift = 0;
    this->disambiguation_store_hash_bits_shift = 0;
}
References ADDRESS_TO_ADDRESS, DESAMBIGUATION_BLOCK_SIZE, disambiguation_load_hash, disambiguation_load_hash_bits_mask, disambiguation_load_hash_bits_shift, disambiguation_store_hash, disambiguation_store_hash_bits_mask, disambiguation_store_hash_bits_shift, LOAD_HASH_SIZE, REGISTER_FORWARD, ROB_SIZE, STORE_HASH_SIZE, and WAIT_CYCLE.
~disambiguation_hashed_t()
disambiguation_hashed_t::~disambiguation_hashed_t ()
Definition at line 23 of file disambiguation_hashed.cpp.
{
    utils_t::template_delete_array<memory_order_buffer_line_t *>(this->disambiguation_load_hash);
    utils_t::template_delete_array<memory_order_buffer_line_t *>(this->disambiguation_store_hash);
}
References disambiguation_load_hash, and disambiguation_store_hash.
Member Function Documentation
allocate()
void disambiguation_hashed_t::allocate () virtual
DISAMBIGUATION OFFSET MASK
Reimplemented from desambiguation_t.
Definition at line 28 of file disambiguation_hashed.cpp.
{
    libconfig::Setting &cfg_root = orcs_engine.configuration->getConfig();
    libconfig::Setting &cfg_processor = cfg_root["PROCESSOR"][0];
    set_ROB_SIZE (cfg_processor["ROB_SIZE"]);
    set_LOAD_HASH_SIZE (cfg_processor["LOAD_HASH_SIZE"]);
    set_STORE_HASH_SIZE (cfg_processor["STORE_HASH_SIZE"]);
    set_DESAMBIGUATION_BLOCK_SIZE (cfg_processor["DESAMBIGUATION_BLOCK_SIZE"]);
    set_ADDRESS_TO_ADDRESS (cfg_processor["ADDRESS_TO_ADDRESS"]);
    set_REGISTER_FORWARD (cfg_processor["REGISTER_FORWARD"]);
    set_WAIT_CYCLE (cfg_processor["WAIT_CYCLE"]);
    // DISAMBIGUATION
    ERROR_ASSERT_PRINTF(utils_t::check_if_power_of_two(LOAD_HASH_SIZE), "Wrong disambiguation_load_hash_size.\n")
    for (uint32_t i = 0; i < utils_t::get_power_of_two(LOAD_HASH_SIZE); i++) {
        this->disambiguation_load_hash_bits_mask |= 1 << i;
    }
    this->disambiguation_load_hash_bits_shift = utils_t::get_power_of_two(DESAMBIGUATION_BLOCK_SIZE);
    this->disambiguation_load_hash_bits_mask <<= this->disambiguation_load_hash_bits_shift;
    this->disambiguation_load_hash = utils_t::template_allocate_initialize_array<memory_order_buffer_line_t *>(LOAD_HASH_SIZE, NULL);
    ERROR_ASSERT_PRINTF(utils_t::check_if_power_of_two(STORE_HASH_SIZE), "Wrong disambiguation_store_hash_size.\n")
    for (uint32_t i = 0; i < utils_t::get_power_of_two(STORE_HASH_SIZE); i++) {
        this->disambiguation_store_hash_bits_mask |= 1 << i;
    }
    this->disambiguation_store_hash_bits_shift <<= utils_t::get_power_of_two(DESAMBIGUATION_BLOCK_SIZE);
    this->disambiguation_store_hash_bits_mask <<= this->disambiguation_store_hash_bits_shift;
    this->disambiguation_store_hash = utils_t::template_allocate_initialize_array<memory_order_buffer_line_t *>(STORE_HASH_SIZE, NULL);
    // Setting values of statistics at Zero
    this->set_stat_disambiguation_read_false_positive(0);
    this->set_stat_disambiguation_write_false_positive(0);
    this->set_stat_address_to_address(0);
}
References utils_t::check_if_power_of_two(), orcs_engine_t::configuration, DESAMBIGUATION_BLOCK_SIZE, disambiguation_load_hash, disambiguation_load_hash_bits_mask, disambiguation_load_hash_bits_shift, disambiguation_store_hash, disambiguation_store_hash_bits_mask, disambiguation_store_hash_bits_shift, ERROR_ASSERT_PRINTF, utils_t::get_power_of_two(), configure_t::getConfig(), LOAD_HASH_SIZE, orcs_engine, and STORE_HASH_SIZE.
make_memory_dependences()
void disambiguation_hashed_t::make_memory_dependences (memory_order_buffer_line_t * mob_line) virtual
Check if LOAD_HASH matches
Check if STORE_HASH matches
Create R -> W, R -> R
Create W -> R, W -> W deps.
Add the new entry into LOAD or STORE hash
Reimplemented from desambiguation_t.
Definition at line 63 of file disambiguation_hashed.cpp.
{
    uint64_t load_hash = new_mob_line->memory_address & this->disambiguation_load_hash_bits_mask;
    uint64_t store_hash = new_mob_line->memory_address & this->disambiguation_store_hash_bits_mask;
    load_hash >>= this->disambiguation_load_hash_bits_shift;
    store_hash >>= this->disambiguation_store_hash_bits_shift;
    memory_order_buffer_line_t *old_mob_line = NULL;
    ERROR_ASSERT_PRINTF(load_hash < LOAD_HASH_SIZE, "load_hash (%lu) > disambiguation_load_hash_size (%d)\n",
                        load_hash, LOAD_HASH_SIZE);
    ERROR_ASSERT_PRINTF(store_hash < STORE_HASH_SIZE, "store_hash (%lu) > disambiguation_store_hash_size (%d)\n",
                        store_hash, STORE_HASH_SIZE);
    if (this->disambiguation_load_hash[load_hash] != NULL) {
        old_mob_line = disambiguation_load_hash[load_hash];
        for (uint32_t k = 0; k < ROB_SIZE; k++) {
            if (old_mob_line->mem_deps_ptr_array[k] == NULL) {
                old_mob_line->mem_deps_ptr_array[k] = new_mob_line;
                new_mob_line->wait_mem_deps_number++;
                if (DEBUG) ORCS_PRINTF ("Disamb make_memory_dependencies(): load %lu -> %lu.\n", old_mob_line->memory_address, new_mob_line->memory_address)
                break;
            }
        }
    }
    if (this->disambiguation_store_hash[store_hash] != NULL) {
        old_mob_line = disambiguation_store_hash[store_hash];
        for (uint32_t k = 0; k < ROB_SIZE; k++) {
            if (old_mob_line->mem_deps_ptr_array[k] == NULL) {
                old_mob_line->mem_deps_ptr_array[k] = new_mob_line;
                new_mob_line->wait_mem_deps_number++;
                if (DEBUG) ORCS_PRINTF ("Disamb make_memory_dependencies(): store %lu -> %lu.\n", old_mob_line->memory_address, new_mob_line->memory_address)
                break;
            }
        }
    }
    if (new_mob_line->memory_operation == MEMORY_OPERATION_READ) {
        this->disambiguation_load_hash[load_hash] = new_mob_line;
    }
    else if (new_mob_line->memory_operation == MEMORY_OPERATION_WRITE) {
        this->disambiguation_store_hash[store_hash] = new_mob_line;
    }
}
References DEBUG, disambiguation_load_hash, disambiguation_load_hash_bits_mask, disambiguation_load_hash_bits_shift, disambiguation_store_hash, disambiguation_store_hash_bits_mask, disambiguation_store_hash_bits_shift, ERROR_ASSERT_PRINTF, LOAD_HASH_SIZE, memory_order_buffer_line_t::mem_deps_ptr_array, memory_order_buffer_line_t::memory_address, memory_request_client_t::memory_operation, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, ORCS_PRINTF, ROB_SIZE, STORE_HASH_SIZE, and memory_order_buffer_line_t::wait_mem_deps_number.
solve_memory_dependences()
void disambiguation_hashed_t::solve_memory_dependences (memory_order_buffer_line_t * mob_line) virtual
Remove pointers from disambiguation_hash Add the new entry into LOAD or STORE hash
SOLVE MEMORY DEPENDENCIES - MOB Send message to acknowledge the dependency is over
All the dependencies are solved
Keep track of false positives
This update the ready cycle, and it is usefull to compute the time each instruction waits for the functional unit
Reimplemented from desambiguation_t.
Definition at line 112 of file disambiguation_hashed.cpp.
{
    //if (mob_line->is_hive) return;
    if (mob_line->memory_operation == MEMORY_OPERATION_READ) {
        uint64_t load_hash = mob_line->memory_address & this->disambiguation_load_hash_bits_mask;
        load_hash >>= this->disambiguation_load_hash_bits_shift;
        ERROR_ASSERT_PRINTF(load_hash < LOAD_HASH_SIZE, "load_hash (%" PRIu64 ") > disambiguation_load_hash_size (%d)\n",
                            load_hash, LOAD_HASH_SIZE);
        if (this->disambiguation_load_hash[load_hash] == mob_line) {
            this->disambiguation_load_hash[load_hash] = NULL;
        }
    } else {
        uint64_t store_hash = mob_line->memory_address & this->disambiguation_store_hash_bits_mask;
        store_hash >>= this->disambiguation_store_hash_bits_shift;
        ERROR_ASSERT_PRINTF(store_hash < STORE_HASH_SIZE, "store_hash (%" PRIu64 ") > disambiguation_store_hash_size (%d)\n",
                            store_hash, STORE_HASH_SIZE);
        if (this->disambiguation_store_hash[store_hash] == mob_line) {
            this->disambiguation_store_hash[store_hash] = NULL;
        }
    }
    for (uint32_t j = 0; j < ROB_SIZE; j++) {
        if (mob_line->mem_deps_ptr_array[j] == NULL) {
            break;
        }
        if (mob_line->mem_deps_ptr_array[j]->memory_address != mob_line->memory_address) {
            if (mob_line->memory_operation == MEMORY_OPERATION_READ) {
                this->add_stat_disambiguation_read_false_positive();
            } else if (mob_line->memory_operation == MEMORY_OPERATION_WRITE) {
                this->add_stat_disambiguation_write_false_positive();
            }
        }
        mob_line->mem_deps_ptr_array[j]->wait_mem_deps_number--;
        if (ADDRESS_TO_ADDRESS == 1) {
            if (mob_line->mem_deps_ptr_array[j]->uop_executed == true &&
                mob_line->mem_deps_ptr_array[j]->wait_mem_deps_number == 0 &&
                mob_line->mem_deps_ptr_array[j]->memory_operation == MEMORY_OPERATION_READ &&
                mob_line->mem_deps_ptr_array[j]->memory_address == mob_line->memory_address &&
                mob_line->mem_deps_ptr_array[j]->memory_size == mob_line->memory_size) {
                this->add_stat_address_to_address();
                mob_line->mem_deps_ptr_array[j]->status = PACKAGE_STATE_READY;
                mob_line->mem_deps_ptr_array[j]->sent = true;
                mob_line->mem_deps_ptr_array[j]->rob_ptr->sent = true;
                mob_line->mem_deps_ptr_array[j]->readyAt = orcs_engine.get_global_cycle() + REGISTER_FORWARD;
                mob_line->mem_deps_ptr_array[j]->forwarded_data=true;
            }
        }
        mob_line->mem_deps_ptr_array[j] = NULL;
    }
}
References ADDRESS_TO_ADDRESS, disambiguation_load_hash, disambiguation_load_hash_bits_mask, disambiguation_load_hash_bits_shift, disambiguation_store_hash, disambiguation_store_hash_bits_mask, disambiguation_store_hash_bits_shift, ERROR_ASSERT_PRINTF, memory_order_buffer_line_t::forwarded_data, orcs_engine_t::get_global_cycle(), LOAD_HASH_SIZE, memory_order_buffer_line_t::mem_deps_ptr_array, memory_order_buffer_line_t::memory_address, memory_request_client_t::memory_operation, MEMORY_OPERATION_READ, MEMORY_OPERATION_WRITE, memory_order_buffer_line_t::memory_size, orcs_engine, PACKAGE_STATE_READY, memory_request_client_t::readyAt, REGISTER_FORWARD, memory_order_buffer_line_t::rob_ptr, ROB_SIZE, memory_order_buffer_line_t::sent, reorder_buffer_line_t::sent, memory_request_client_t::status, STORE_HASH_SIZE, memory_order_buffer_line_t::uop_executed, and memory_order_buffer_line_t::wait_mem_deps_number.
statistics()
void disambiguation_hashed_t::statistics () virtual
Reimplemented from desambiguation_t.
Definition at line 174 of file disambiguation_hashed.cpp.
{
    bool close = false;
    FILE *output = stdout;
    if(orcs_engine.output_file_name != NULL) {
        output = fopen(orcs_engine.output_file_name,"a+");
        close=true;
    }
    if (output != NULL){
            utils_t::largeSeparator(output);
            fprintf(output,"#Memory Disambiguation\n");
            utils_t::largeSeparator(output);
            fprintf(output,"Total_Read_false_Positives:       %lu\n", this->get_stat_disambiguation_read_false_positive());
            fprintf(output,"Total_Write_false_Positives:      %lu\n", this->get_stat_disambiguation_write_false_positive());
            fprintf(output,"Total_Resolve_Address_to_Address: %lu\n",this->get_stat_address_to_address());
            utils_t::largeSeparator(output);
    }
    if(close) fclose(output);
}
References utils_t::largeSeparator(), orcs_engine, and orcs_engine_t::output_file_name.
The documentation for this class was generated from the following files:
processor/memory_disambiguation/disambiguation_hashed.hpp
processor/memory_disambiguation/disambiguation_hashed.cpp