OrCS: memory_controller_t Class Reference
memory_controller_t Class Reference
#include <memory_controller.hpp>
Public Member Functions
void allocate ()
uint64_t get_column (uint64_t addr)
uint64_t get_channel (uint64_t addr)
uint64_t get_bank (uint64_t addr)
uint64_t get_row (uint64_t address)
memory_controller_t ()
~memory_controller_t ()
void clock ()
void statistics ()
void set_masks ()
uint64_t requestDRAM (memory_package_t *request)
float get_row_buffer_miss_ratio ()
INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_AL) INSTANTIATE_GET_SET_ADD(uint32_t
TIMING_CAS INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_CCD) INSTANTIATE_GET_SET_ADD(uint32_t
TIMING_CAS TIMING_CWD INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_FAW) INSTANTIATE_GET_SET_ADD(uint32_t
TIMING_CAS TIMING_CWD TIMING_RAS INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_RC) INSTANTIATE_GET_SET_ADD(uint32_t
TIMING_CAS TIMING_CWD TIMING_RAS TIMING_RCD INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_RP) INSTANTIATE_GET_SET_ADD(uint32_t
TIMING_CAS TIMING_CWD TIMING_RAS TIMING_RCD TIMING_RRD INSTANTIATE_GET_SET_ADD (uint32_t, TIMING_RTP) INSTANTIATE_GET_SET_ADD(uint32_t
Private Attributes
uint64_t requests_made
uint64_t operations_executed
uint64_t requests_llc
uint64_t requests_hive
uint64_t requests_vima
uint64_t requests_prefetcher
uint64_t row_buffer_miss
uint64_t row_buffer_hit
uint64_t channel_bits_mask
uint64_t rank_bits_mask
uint64_t bank_bits_mask
uint64_t row_bits_mask
uint64_t colrow_bits_mask
uint64_t colbyte_bits_mask
uint64_t not_column_bits_mask
uint64_t channel_bits_shift
uint64_t colbyte_bits_shift
uint64_t colrow_bits_shift
uint64_t bank_bits_shift
uint64_t row_bits_shift
uint64_t controller_bits_shift
std::vector< memory_package_t * > working
uint64_t latency_burst
uint64_t * total_latency
uint64_t * total_operations
uint64_t * min_wait_operations
uint64_t * max_wait_operations
uint64_t wait_time
uint32_t BANK
uint32_t BANK_ROW_BUFFER_SIZE
uint32_t BURST_WIDTH
uint32_t CHANNEL
uint32_t WAIT_CYCLE
uint32_t LINE_SIZE
float CORE_TO_BUS_CLOCK_RATIO
uint32_t TIMING_AL
uint32_t TIMING_CAS
uint32_t TIMING_CCD
uint32_t TIMING_CWD
uint32_t TIMING_FAW
uint32_t TIMING_RAS
uint32_t TIMING_RC
uint32_t TIMING_RCD
uint32_t TIMING_RP
uint32_t TIMING_RRD
uint32_t TIMING_RTP
uint32_t TIMING_WR
uint32_t TIMING_WTR
memory_channel_t * channels
uint64_t i
Detailed Description
Definition at line 4 of file memory_controller.hpp.
Constructor & Destructor Documentation
memory_controller_t()
memory_controller_t::memory_controller_t ()
Definition at line 4 of file memory_controller.cpp.
{
    this->requests_made = 0; //Data Requests made
    this->operations_executed = 0; // number of operations executed
    this->requests_llc = 0; //Data Requests made to LLC
    this->requests_hive = 0;
    this->requests_vima = 0;
    this->requests_prefetcher = 0; //Data Requests made by prefetcher
    this->row_buffer_miss = 0; //Counter row buffer misses
    this->row_buffer_hit = 0;
    this->channel_bits_mask = 0;
    this->rank_bits_mask = 0;
    this->bank_bits_mask = 0;
    this->row_bits_mask = 0;
    this->colrow_bits_mask = 0;
    this->colbyte_bits_mask = 0;
    this->not_column_bits_mask = 0;
    // Shifts bits
    this->channel_bits_shift = 0;
    this->colbyte_bits_shift = 0;
    this->colrow_bits_shift = 0;
    this->bank_bits_shift = 0;
    this->row_bits_shift = 0;
    this->controller_bits_shift = 0;
    this->total_latency = NULL;
    this->total_operations = NULL;
    this->CHANNEL = 0;
    this->WAIT_CYCLE = 0;
    this->LINE_SIZE = 0;
    this->CORE_TO_BUS_CLOCK_RATIO = 0.0;
    this->TIMING_AL = 0;     // Added Latency for column accesses
    this->TIMING_CAS = 0;    // Column Access Strobe (CL) latency
    this->TIMING_CCD = 0;    // Column to Column Delay
    this->TIMING_CWD = 0;    // Column Write Delay (CWL) or simply WL
    this->TIMING_FAW = 0;   // Four (row) Activation Window
    this->TIMING_RAS = 0;   // Row Access Strobe
    this->TIMING_RC = 0;    // Row Cycle
    this->TIMING_RCD = 0;    // Row to Column comand Delay
    this->TIMING_RP = 0;     // Row Precharge
    this->TIMING_RRD = 0;    // Row activation to Row activation Delay
    this->TIMING_RTP = 0;    // Read To Precharge
    this->TIMING_WR = 0;    // Write Recovery time
    this->TIMING_WTR = 0;
    this->channels = NULL;
    this->i = 0;
}
References bank_bits_mask, bank_bits_shift, CHANNEL, channel_bits_mask, channel_bits_shift, channels, colbyte_bits_mask, colbyte_bits_shift, colrow_bits_mask, colrow_bits_shift, controller_bits_shift, CORE_TO_BUS_CLOCK_RATIO, i, LINE_SIZE, not_column_bits_mask, operations_executed, rank_bits_mask, requests_hive, requests_llc, requests_made, requests_prefetcher, requests_vima, row_bits_mask, row_bits_shift, row_buffer_hit, row_buffer_miss, TIMING_AL, TIMING_CAS, TIMING_CCD, TIMING_CWD, TIMING_FAW, TIMING_RAS, TIMING_RC, TIMING_RCD, TIMING_RP, TIMING_RRD, TIMING_RTP, TIMING_WR, TIMING_WTR, total_latency, total_operations, and WAIT_CYCLE.
~memory_controller_t()
memory_controller_t::~memory_controller_t ()
Definition at line 56 of file memory_controller.cpp.
{
    delete[] this->total_operations;
    delete[] this->total_latency;
    delete[] this->min_wait_operations;
    delete[] this->max_wait_operations;
    delete[] this->channels;
}
References channels, max_wait_operations, min_wait_operations, total_latency, and total_operations.
Member Function Documentation
allocate()
void memory_controller_t::allocate ()
Definition at line 77 of file memory_controller.cpp.
{
    libconfig::Setting &cfg_root = orcs_engine.configuration->getConfig();
    libconfig::Setting &cfg_memory_ctrl = cfg_root["MEMORY_CONTROLLER"];
    set_BANK (cfg_memory_ctrl["BANK"]);
    set_BANK_ROW_BUFFER_SIZE (cfg_memory_ctrl["BANK_ROW_BUFFER_SIZE"]);
    set_CHANNEL (cfg_memory_ctrl["CHANNEL"]);
    set_BURST_WIDTH (cfg_memory_ctrl["BURST_WIDTH"]);
    set_LINE_SIZE (cfg_memory_ctrl["LINE_SIZE"]);
    set_WAIT_CYCLE (cfg_memory_ctrl["WAIT_CYCLE"]);
    set_CORE_TO_BUS_CLOCK_RATIO (cfg_memory_ctrl["CORE_TO_BUS_CLOCK_RATIO"]);
    set_latency_burst (ceil ((LINE_SIZE/BURST_WIDTH) * this->CORE_TO_BUS_CLOCK_RATIO));
    this->total_latency = new uint64_t [MEMORY_OPERATION_LAST]();
    this->total_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    this->min_wait_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    for (i = 0; i < MEMORY_OPERATION_LAST; i++) this->min_wait_operations[i] = UINT64_MAX;
    this->max_wait_operations = new uint64_t [MEMORY_OPERATION_LAST]();
    set_TIMING_AL (cfg_memory_ctrl["TIMING_AL"]);     // Added Latency for column accesses
    set_TIMING_CAS (cfg_memory_ctrl["TIMING_CAS"]);    // Column Access Strobe (CL]) latency
    set_TIMING_CCD (cfg_memory_ctrl["TIMING_CCD"]);    // Column to Column Delay
    set_TIMING_CWD (cfg_memory_ctrl["TIMING_CWD"]);    // Column Write Delay (CWL]) or simply WL
    set_TIMING_FAW (cfg_memory_ctrl["TIMING_FAW"]);   // Four (row]) Activation Window
    set_TIMING_RAS (cfg_memory_ctrl["TIMING_RAS"]);   // Row Access Strobe
    set_TIMING_RC (cfg_memory_ctrl["TIMING_RC"]);    // Row Cycle
    set_TIMING_RCD (cfg_memory_ctrl["TIMING_RCD"]);    // Row to Column comand Delay
    set_TIMING_RP (cfg_memory_ctrl["TIMING_RP"]);     // Row Precharge
    set_TIMING_RRD (cfg_memory_ctrl["TIMING_RRD"]);    // Row activation to Row activation Delay
    set_TIMING_RTP (cfg_memory_ctrl["TIMING_RTP"]);    // Read To Precharge
    set_TIMING_WR (cfg_memory_ctrl["TIMING_WR"]);    // Write Recovery time
    set_TIMING_WTR (cfg_memory_ctrl["TIMING_WTR"]);
    this->channels = new memory_channel_t[CHANNEL]();
    for (i = 0; i < this->CHANNEL; i++) this->channels[i].allocate();
    for (i = 0; i < this->CHANNEL; i++){
        channels[i].set_latency_burst (this->latency_burst);
        channels[i].set_TIMING_AL (ceil (this->TIMING_AL * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_CAS (ceil (this->TIMING_CAS * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_CCD (ceil (this->TIMING_CCD * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_CWD (ceil (this->TIMING_CWD * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_FAW (ceil (this->TIMING_FAW * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RAS (ceil (this->TIMING_RAS * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RC (ceil (this->TIMING_RC * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RCD (ceil (this->TIMING_RCD * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RP (ceil (this->TIMING_RP * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RRD (ceil (this->TIMING_RRD * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_RTP (ceil (this->TIMING_RTP * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_WR (ceil (this->TIMING_WR * this->CORE_TO_BUS_CLOCK_RATIO));
        channels[i].set_TIMING_WTR (ceil (this->TIMING_WTR * this->CORE_TO_BUS_CLOCK_RATIO));
    }
    this->set_masks();
}
References allocate(), BURST_WIDTH, CHANNEL, channels, orcs_engine_t::configuration, CORE_TO_BUS_CLOCK_RATIO, configure_t::getConfig(), i, latency_burst, LINE_SIZE, max_wait_operations, MEMORY_OPERATION_LAST, min_wait_operations, orcs_engine, set_masks(), TIMING_AL, TIMING_CAS, TIMING_CCD, TIMING_CWD, TIMING_FAW, TIMING_RAS, TIMING_RC, TIMING_RCD, TIMING_RP, TIMING_RRD, TIMING_RTP, TIMING_WR, TIMING_WTR, total_latency, and total_operations.
clock()
void memory_controller_t::clock ()
Definition at line 178 of file memory_controller.cpp.
{
    for (i = 0; i < this->CHANNEL; i++) this->channels[i].clock();
    if (working.size() == 0) return;
    for (i = 0; i < working.size(); i++){
        if (working[i]->status != PACKAGE_STATE_DRAM_FETCH && working[i]->status != PACKAGE_STATE_DRAM_READY){
            if (this->channels[get_channel (working[i]->memory_address)].addRequest (working[i])) {
                working[i]->ram_cycle = orcs_engine.get_global_cycle();
                working[i]->updatePackageDRAMFetch (0);
            }
        } else if (working[i]->status == PACKAGE_STATE_DRAM_READY && working[i]->readyAt <= orcs_engine.get_global_cycle()){
            wait_time = (orcs_engine.get_global_cycle() - working[i]->ram_cycle);
            #if MEMORY_DEBUG
                ORCS_PRINTF ("[MEMC] %lu %lu %s finishes at main memory! Took %lu cycles.\n", orcs_engine.get_global_cycle(), working[i]->memory_address, get_enum_memory_operation_char (working[i]->memory_operation), wait_time)
            #endif
            working[i]->updatePackageWait (1);
            this->total_operations[working[i]->memory_operation]++;
            if (wait_time < this->min_wait_operations[working[i]->memory_operation]) this->min_wait_operations[working[i]->memory_operation] = wait_time;
            if (wait_time > this->min_wait_operations[working[i]->memory_operation]) this->max_wait_operations[working[i]->memory_operation] = wait_time;
            this->total_latency[working[i]->memory_operation] += wait_time;
            working.erase(std::remove(working.begin(), working.end(), working[i]), working.end());
            working.shrink_to_fit();
        }
    }
}
References CHANNEL, channels, clock(), get_channel(), get_enum_memory_operation_char(), orcs_engine_t::get_global_cycle(), i, max_wait_operations, min_wait_operations, orcs_engine, ORCS_PRINTF, PACKAGE_STATE_DRAM_FETCH, PACKAGE_STATE_DRAM_READY, total_latency, total_operations, wait_time, and working.
get_bank()
uint64_t memory_controller_t::get_bank (uint64_t addr) inline
Definition at line 92 of file memory_controller.hpp.
{
            return (addr & this->bank_bits_mask) >> this->bank_bits_shift;
        }
References bank_bits_shift.
get_channel()
uint64_t memory_controller_t::get_channel (uint64_t addr) inline
Definition at line 88 of file memory_controller.hpp.
{
            return (addr & this->channel_bits_mask) >> this->channel_bits_shift;
        }
References channel_bits_shift.
get_column()
uint64_t memory_controller_t::get_column (uint64_t addr) inline
Definition at line 84 of file memory_controller.hpp.
{
            return (addr & this->colrow_bits_mask) >> this->colrow_bits_shift;
        }
References colrow_bits_shift.
get_row()
uint64_t memory_controller_t::get_row (uint64_t address) inline
Definition at line 96 of file memory_controller.hpp.
{
            return (address & this->not_column_bits_mask);
        }
requestDRAM()
uint64_t memory_controller_t::requestDRAM (memory_package_t * request)
Definition at line 254 of file memory_controller.cpp.
{
    if (request != NULL) {
        this->add_requests_made();
        if (request->is_hive) this->add_requests_hive();
        if (request->is_vima) this->add_requests_vima();
        request->sent_to_ram = true;
        this->working.push_back (request);
        this->working.shrink_to_fit();
        #if DEBUG
            ORCS_PRINTF ("Memory Controller requestDRAM(): receiving memory request from uop %lu, %s.\n", request->uop_number, get_enum_memory_operation_char (request->memory_operation))
        #endif
        #if MEMORY_DEBUG
            ORCS_PRINTF ("[MEMC] %lu %lu %s enters.\n", orcs_engine.get_global_cycle(), request->memory_address, get_enum_memory_operation_char (request->memory_operation))
        #endif
        return 0;
    }
    return 0;
}
References get_enum_memory_operation_char(), orcs_engine_t::get_global_cycle(), memory_package_t::is_hive, memory_package_t::is_vima, memory_package_t::memory_address, memory_package_t::memory_operation, orcs_engine, ORCS_PRINTF, memory_package_t::sent_to_ram, memory_package_t::uop_number, and working.
set_masks()
void memory_controller_t::set_masks ()
COLBYTE MASK
COLROW MASK
CHANNEL MASK
BANK MASK
ROW MASK
Definition at line 205 of file memory_controller.cpp.
{
    ERROR_ASSERT_PRINTF(CHANNEL > 1 && utils_t::check_if_power_of_two(CHANNEL),"Wrong number of memory_channels (%u).\n",CHANNEL);
    this->channel_bits_shift=0;
    this->colbyte_bits_shift=0;
    this->colrow_bits_shift=0;
    this->bank_bits_shift=0;
    this->row_bits_shift=0;
    this->colbyte_bits_shift = 0;
    this->channel_bits_mask = 0;
    this->bank_bits_mask = 0;
    this->rank_bits_mask = 0;
    this->row_bits_mask = 0;
    this->colrow_bits_mask = 0;
    this->colbyte_bits_mask = 0;
    // =======================================================
    this->controller_bits_shift = 0;
    this->colbyte_bits_shift = 0;
    this->colrow_bits_shift = utils_t::get_power_of_two(this->LINE_SIZE);
    this->channel_bits_shift = utils_t::get_power_of_two(this->BANK_ROW_BUFFER_SIZE);
    this->bank_bits_shift = this->channel_bits_shift + utils_t::get_power_of_two(this->CHANNEL);
    this->row_bits_shift = this->bank_bits_shift + utils_t::get_power_of_two(this->BANK);
    for (i = 0; i < utils_t::get_power_of_two(this->LINE_SIZE); i++) {
        this->colbyte_bits_mask |= 1 << (i + this->colbyte_bits_shift);
    }
    for (i = 0; i < utils_t::get_power_of_two(this->BANK_ROW_BUFFER_SIZE / this->LINE_SIZE); i++) {
        this->colrow_bits_mask |= 1 << (i + this->colrow_bits_shift);
    }
    this->not_column_bits_mask = ~(colbyte_bits_mask | colrow_bits_mask);
    for (i = 0; i < utils_t::get_power_of_two(this->CHANNEL); i++) this->channel_bits_mask |= 1 << (i + channel_bits_shift);
    for (i = 0; i < utils_t::get_power_of_two(this->BANK); i++) this->bank_bits_mask |= 1 << (i + bank_bits_shift);
    for (i = row_bits_shift; i < utils_t::get_power_of_two((uint64_t)INT64_MAX+1); i++) {
        this->row_bits_mask |= 1 << i;
    }
}
References BANK, bank_bits_mask, bank_bits_shift, BANK_ROW_BUFFER_SIZE, CHANNEL, channel_bits_mask, channel_bits_shift, utils_t::check_if_power_of_two(), colbyte_bits_mask, colbyte_bits_shift, colrow_bits_mask, colrow_bits_shift, controller_bits_shift, ERROR_ASSERT_PRINTF, utils_t::get_power_of_two(), i, LINE_SIZE, not_column_bits_mask, rank_bits_mask, row_bits_mask, and row_bits_shift.
statistics()
void memory_controller_t::statistics ()
Definition at line 133 of file memory_controller.cpp.
{
    FILE *output = stdout;
    bool close = false;
    if(orcs_engine.output_file_name != NULL){
        close=true;
        output = fopen(orcs_engine.output_file_name,"a+");
    }
    if (output != NULL){
        uint32_t total_rb_hits = 0, total_rb_misses = 0;
        utils_t::largestSeparator(output);
        fprintf(output,"#Memory Controller\n");
        utils_t::largestSeparator(output);
        fprintf(output,"Requests_Made:               %lu\n",this->get_requests_made());
        if (this->get_requests_prefetcher() > 0)  fprintf(output,"Requests_from_Prefetcher:    %lu\n",this->get_requests_prefetcher());
        fprintf(output,"Requests_from_LLC:           %lu\n",this->get_requests_llc());
        if (this->get_requests_hive() > 0) fprintf(output,"Requests_from_HIVE:          %lu\n",this->get_requests_hive());
        if (this->get_requests_vima() > 0) fprintf(output,"Requests_from_VIMA:          %lu\n",this->get_requests_vima());
        for (i = 0; i < CHANNEL; i++){
            if (i > 9) {
                fprintf(output,"Row_Buffer_Hit,  Channel %lu: %lu\n",i,this->channels[i].get_stat_row_buffer_hit());
                fprintf(output,"Row_Buffer_Miss, Channel %lu: %lu\n",i,this->channels[i].get_stat_row_buffer_miss());
            } else {
                fprintf(output,"Row_Buffer_Hit,  Channel  %lu: %lu\n",i,this->channels[i].get_stat_row_buffer_hit());
                fprintf(output,"Row_Buffer_Miss, Channel  %lu: %lu\n",i,this->channels[i].get_stat_row_buffer_miss());
            }
            total_rb_hits += this->channels[i].get_stat_row_buffer_hit();
            total_rb_misses += this->channels[i].get_stat_row_buffer_miss();
        }
        fprintf(output,"Row_Buffer Total_Hits:       %u\n",total_rb_hits);
        fprintf(output,"Row_Buffer_Total_Misses:     %u\n",total_rb_misses);
        fprintf(output,"Row_Buffer_Miss_Ratio:       %f\n", (float) total_rb_misses/this->get_requests_made());
        for (i = 0; i < MEMORY_OPERATION_LAST; i++){
            if (this->total_operations[i] > 0) {
                fprintf(output,"%s_Tot._Latency:          %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->total_latency[i]);
                fprintf(output,"%s_Avg._Latency:          %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->total_latency[i]/this->total_operations[i]);
                fprintf(output,"%s_Min._Latency:          %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->min_wait_operations[i]);
                fprintf(output,"%s_Max._Latency:          %lu\n", get_enum_memory_operation_char ((memory_operation_t) i), this->max_wait_operations[i]);
            }
        }
        utils_t::largestSeparator(output);
        if(close) fclose(output);
    }
}
References CHANNEL, channels, get_enum_memory_operation_char(), i, utils_t::largestSeparator(), max_wait_operations, MEMORY_OPERATION_LAST, min_wait_operations, orcs_engine, orcs_engine_t::output_file_name, total_latency, and total_operations.
The documentation for this class was generated from the following files:
main_memory/memory_controller.hpp
main_memory/memory_controller.cpp