OrCS: stride_prefetcher_t Class Reference
stride_prefetcher_t Class Reference
#include <stride_prefetcher.hpp>
Public Member Functions
stride_prefetcher_t ()
~stride_prefetcher_t ()
uint32_t searchLRU ()
void allocate (uint32_t NUMBER_OF_PROCESSORS)
int32_t searchPattern (uint64_t pc)
uint32_t installStride (uint64_t pc, uint64_t address)
uint32_t updateStride (uint64_t pc, uint64_t address, status_stride_prefetcher_t status)
int64_t verify (uint64_t pc, uint64_t address)
void statistics ()
Public Attributes
stride_table_t * stride_table
Private Attributes
uint32_t DISTANCE
uint32_t STRIDE_TABLE_SIZE
Detailed Description
Definition at line 4 of file stride_prefetcher.hpp.
Constructor & Destructor Documentation
stride_prefetcher_t()
stride_prefetcher_t::stride_prefetcher_t ()
Definition at line 3 of file stride_prefetcher.cpp.
{}
~stride_prefetcher_t()
stride_prefetcher_t::~stride_prefetcher_t ()
Definition at line 5 of file stride_prefetcher.cpp.
{
    if(this->stride_table) delete[] &this->stride_table;
}
References stride_table.
Member Function Documentation
allocate()
void stride_prefetcher_t::allocate (uint32_t NUMBER_OF_PROCESSORS)
Definition at line 9 of file stride_prefetcher.cpp.
{
    libconfig::Setting &cfg_root = orcs_engine.configuration->getConfig();
    libconfig::Setting &cfg_prefetcher = cfg_root["PREFETCHER"];
    set_DISTANCE(cfg_prefetcher["DISTANCE"]);
    set_STRIDE_TABLE_SIZE (NUMBER_OF_PROCESSORS * 32);
    this->stride_table = new stride_table_t[STRIDE_TABLE_SIZE]();
}
References orcs_engine_t::configuration, configure_t::getConfig(), orcs_engine, stride_table, and STRIDE_TABLE_SIZE.
installStride()
uint32_t stride_prefetcher_t::installStride (uint64_t pc, uint64_t address)
Definition at line 37 of file stride_prefetcher.cpp.
{
    uint64_t tag = pc;
    for (size_t i = 0; i < STRIDE_TABLE_SIZE; i++) {
        if(this->stride_table[i].status == INVALID){
            this->stride_table[i].tag = tag;
            this->stride_table[i].last_address = address;
            this->stride_table[i].stride = 0;
            this->stride_table[i].status = TRAINING;
            this->stride_table[i].lru = orcs_engine.get_global_cycle();
            return OK;
        }
    }
    uint32_t idx = this->searchLRU();
    this->stride_table[idx].tag = tag;
    this->stride_table[idx].last_address = address;
    this->stride_table[idx].stride = 0;
    this->stride_table[idx].status = TRAINING;
    this->stride_table[idx].lru = orcs_engine.get_global_cycle();
    return OK;
}
References orcs_engine_t::get_global_cycle(), INVALID, stride_table_t::last_address, stride_table_t::lru, OK, orcs_engine, searchLRU(), stride_table_t::status, stride_table_t::stride, stride_table, STRIDE_TABLE_SIZE, stride_table_t::tag, and TRAINING.
searchLRU()
uint32_t stride_prefetcher_t::searchLRU () inline
Definition at line 18 of file stride_prefetcher.cpp.
{
    uint32_t idx = 0;
    for (uint32_t i = 1; i < STRIDE_TABLE_SIZE; i++){
        idx = (this->stride_table[idx].lru < this->stride_table[i].lru)? idx : i;
    }
    return idx;
}
References stride_table_t::lru, stride_table, and STRIDE_TABLE_SIZE.
searchPattern()
int32_t stride_prefetcher_t::searchPattern (uint64_t pc)
Definition at line 26 of file stride_prefetcher.cpp.
{
    uint64_t tag = pc;
    for (uint32_t i = 0; i < STRIDE_TABLE_SIZE; i++) {
        if((this->stride_table[i].tag == tag)&&(this->stride_table[i].status != INVALID)) {
            this->stride_table[i].lru = orcs_engine.get_global_cycle();
            return i;
        }
    }
    return MISS;
}
References orcs_engine_t::get_global_cycle(), INVALID, stride_table_t::lru, MISS, orcs_engine, stride_table, and STRIDE_TABLE_SIZE.
updateStride()
uint32_t stride_prefetcher_t::updateStride (uint64_t pc, uint64_t address, status_stride_prefetcher_t status)
Definition at line 58 of file stride_prefetcher.cpp.
{
    uint64_t tag = pc;
    for (size_t i = 0; i < STRIDE_TABLE_SIZE; i++) {
        if(this->stride_table[i].tag == tag){
            this->stride_table[i].stride = labs(this->stride_table[i].last_address - address);
            this->stride_table[i].last_address = address;
            this->stride_table[i].status = status;
            this->stride_table[i].lru = orcs_engine.get_global_cycle();
            return OK;
        }
    }
    return OK;
}
References orcs_engine_t::get_global_cycle(), stride_table_t::last_address, stride_table_t::lru, OK, orcs_engine, stride_table_t::status, stride_table_t::stride, stride_table, and STRIDE_TABLE_SIZE.
verify()
int64_t stride_prefetcher_t::verify (uint64_t pc, uint64_t address)
Definition at line 72 of file stride_prefetcher.cpp.
{
    int64_t new_address = POSITION_FAIL;
    int32_t idx = this->searchPattern(pc);
    if(idx == MISS) {
        this->installStride(pc,address);
    } else {
        uint64_t anterior = this->stride_table[idx].last_address - this->stride_table[idx].stride;
        uint64_t posterior = this->stride_table[idx].last_address + this->stride_table[idx].stride;
        if((address >= anterior)||(address <=posterior)) {
            if(this->stride_table[idx].status == INVALID) {
                this->updateStride(pc,address,TRAINING);
            }
            if(this->stride_table[idx].status == ACTIVE) {
                uint32_t stride = labs(address-this->stride_table[idx].last_address);
                if(stride == this->stride_table[idx].stride) {
                //verifica se ta instalada
                new_address = (DISTANCE*stride)+this->stride_table[idx].last_address;
                this->updateStride(pc,address,ACTIVE);
                } else {
                    this->updateStride(pc,address,INVALID);
                }
            }
            if(this->stride_table[idx].status == TRAINING) {
                    this->updateStride(pc,address,ACTIVE);
            }
        }
    }
    return new_address;
}
References ACTIVE, DISTANCE, installStride(), INVALID, stride_table_t::last_address, MISS, POSITION_FAIL, searchPattern(), stride_table_t::stride, stride_table, TRAINING, and updateStride().
The documentation for this class was generated from the following files:
prefetcher/stride_prefetcher.hpp
prefetcher/stride_prefetcher.cpp