OrCS: memory_order_buffer_line_t Class Reference
memory_order_buffer_line_t Class Reference
#include <memory_order_buffer_line.hpp>
Public Member Functions
memory_order_buffer_line_t ()
Methods.
~memory_order_buffer_line_t ()
void package_clean ()
std::string content_to_string ()
Public Member Functions inherited from memory_request_client_t
memory_request_client_t ()
virtual ~memory_request_client_t ()
virtual void updatePackageUntreated (uint32_t stallTime)
virtual void updatePackageReady (uint32_t stallTime)
virtual void updatePackageWait (uint32_t stallTime)
virtual void updatePackageFree (uint32_t stallTime)
Static Public Member Functions
static int32_t find_free (memory_order_buffer_line_t *input_array, uint32_t size_array)
STATIC METHODS.
static int32_t find_old_request_state_ready (memory_order_buffer_line_t *input_array, uint32_t size_array, package_state_t state)
static void printAllOrder (memory_order_buffer_line_t *input_array, uint32_t size_array, uint32_t start, uint32_t end)
Public Attributes
uint64_t opcode_address
uint64_t memory_address
uint32_t memory_size
bool is_hive
uint64_t hive_read1
uint64_t hive_read2
uint64_t hive_write
bool is_vima
uint64_t vima_read1
uint64_t vima_read2
uint64_t vima_write
reorder_buffer_line_t * rob_ptr
bool uop_executed
Memory Dependencies Control.
uint64_t uop_number
uint64_t cycle_send_request
uint64_t readyToGo
uint32_t wait_mem_deps_number
Cycles of waiting.
memory_order_buffer_line_t ** mem_deps_ptr_array
Must wait BEFORE execution.
uint32_t processor_id
Elements to wake-up AFTER execution.
uint64_t cycle_sent_to_DRAM
bool processed
bool sent
bool forwarded_data
bool waiting_DRAM
bool core_generate_miss
Public Attributes inherited from memory_request_client_t
package_state_t status
uint32_t readyAt
memory_operation_t memory_operation
bool waiting_DRAM
Detailed Description
Definition at line 1 of file memory_order_buffer_line.hpp.
Constructor & Destructor Documentation
memory_order_buffer_line_t()
memory_order_buffer_line_t::memory_order_buffer_line_t ()
Methods.
Definition at line 5 of file memory_order_buffer_line.cpp.
{
    this->package_clean();
    this->mem_deps_ptr_array = NULL;
}
References mem_deps_ptr_array, and package_clean().
~memory_order_buffer_line_t()
memory_order_buffer_line_t::~memory_order_buffer_line_t ()
Definition at line 11 of file memory_order_buffer_line.cpp.
{
    //utils_t::template_delete_array<memory_order_buffer_line_t*>(mem_deps_ptr_array);
}
Member Function Documentation
content_to_string()
std::string memory_order_buffer_line_t::content_to_string ()
Definition at line 46 of file memory_order_buffer_line.cpp.
{
    std::string content_string;
    content_string = "";
    if(this->status == PACKAGE_STATE_FREE){
        return content_string;
    }
    content_string = content_string + " |Uop Number:" + utils_t::uint64_to_string(this->uop_number);
    content_string = content_string + " |Exec:" + utils_t::uint64_to_string(this->opcode_address);
    content_string = content_string + " |Executed:" + utils_t::bool_to_string(this->uop_executed);
    content_string = content_string + " |Mem. Operation:" +  get_enum_memory_operation_char(this->memory_operation);
    content_string = content_string + " |Mem. Address:" +  utils_t::uint64_to_string(this->memory_address);
    content_string = content_string + " |Mem. Size:" +  utils_t::uint64_to_string(this->memory_size);
    content_string = content_string + " |Status:" +  get_enum_package_state_char(this->status);
    content_string = content_string + " |Wait Mem Deps:" + utils_t::int32_to_string(this->wait_mem_deps_number);
    content_string = content_string + " |Ready At:" +  utils_t::uint64_to_string(this->readyAt);
    content_string = content_string + " |Ready To Go:" +  utils_t::uint64_to_string(this->readyToGo) + "\n";
    content_string = content_string + " | CONTROL FLAGS: \n";
    content_string = content_string + " |Sent:"+utils_t::bool_to_string(this->sent);
    content_string = content_string + " |Processed:"+utils_t::bool_to_string(this->processed);
    content_string = content_string + " |Forwarded_data:"+utils_t::bool_to_string(this->forwarded_data);
    content_string = content_string + " |Waiting_DRAM:"+utils_t::bool_to_string(this->waiting_DRAM);
    content_string = content_string + " |Core Miss:"+utils_t::bool_to_string(this->core_generate_miss);
    content_string = content_string + " |Core ID:" + utils_t::int32_to_string(this->processor_id);
    return content_string;
}
References utils_t::bool_to_string(), core_generate_miss, forwarded_data, get_enum_memory_operation_char(), get_enum_package_state_char(), utils_t::int32_to_string(), memory_address, memory_request_client_t::memory_operation, memory_size, opcode_address, PACKAGE_STATE_FREE, processed, processor_id, memory_request_client_t::readyAt, readyToGo, sent, memory_request_client_t::status, utils_t::uint64_to_string(), uop_executed, uop_number, wait_mem_deps_number, and waiting_DRAM.
find_free()
int32_t memory_order_buffer_line_t::find_free (memory_order_buffer_line_t * input_array, uint32_t size_array) static
STATIC METHODS.
Definition at line 76 of file memory_order_buffer_line.cpp.
{
    for (uint32_t i = 0; i < size_array ; i++) {
        if (input_array[i].status == PACKAGE_STATE_FREE){
            return i;
        }
    }
    return POSITION_FAIL;
}
References PACKAGE_STATE_FREE, POSITION_FAIL, and memory_request_client_t::status.
find_old_request_state_ready()
int32_t memory_order_buffer_line_t::find_old_request_state_ready (memory_order_buffer_line_t * input_array, uint32_t size_array, package_state_t state) static
Find the oldest UOP inside the MOB.... and it have 0 deps.
Definition at line 85 of file memory_order_buffer_line.cpp.
{
    int32_t old_pos = POSITION_FAIL;
    // uint64_t old_uop_number = UINT64_MAX;
    uint64_t old_uop_number = std::numeric_limits<uint64_t>::max();
    for (uint32_t i = 0; i < size_array ; i++) {
        if (input_array[i].status == state &&
        input_array[i].uop_number < old_uop_number &&
        input_array[i].wait_mem_deps_number <= 0 &&
        input_array[i].uop_executed == true
        && input_array[i].readyToGo <= orcs_engine.get_global_cycle()
        ) {
            old_uop_number = input_array[i].uop_number;
            old_pos = i;
        }
    }
    return old_pos;
}
References orcs_engine_t::get_global_cycle(), orcs_engine, POSITION_FAIL, readyToGo, memory_request_client_t::status, uop_executed, uop_number, and wait_mem_deps_number.
package_clean()
void memory_order_buffer_line_t::package_clean ()
rob pointer
Definition at line 17 of file memory_order_buffer_line.cpp.
{
        this->opcode_address=0;
        this->memory_address=0;
        this->memory_size=0;
        this->is_hive = false;
        this->hive_read1 = 0;
        this->hive_read2 = 0;
        this->hive_write = 0;
        this->is_vima = false;
        this->rob_ptr=NULL;
        this->uop_executed=false;
        this->uop_number = 0;
        this->readyAt = orcs_engine.get_global_cycle();
        this->status = PACKAGE_STATE_FREE;
        this->memory_operation = MEMORY_OPERATION_FREE;
        this->readyToGo = orcs_engine.get_global_cycle();
        this->cycle_send_request = orcs_engine.get_global_cycle();
        this->wait_mem_deps_number = 0;
        //control variables
        this->processed = false;
        this->sent=false;
        this->forwarded_data=false;
        this->waiting_DRAM=false;
        this->core_generate_miss=false;
        this->processor_id = 0;
        this->cycle_sent_to_DRAM = orcs_engine.get_global_cycle();
}
References core_generate_miss, cycle_send_request, cycle_sent_to_DRAM, forwarded_data, orcs_engine_t::get_global_cycle(), hive_read1, hive_read2, hive_write, is_hive, is_vima, memory_address, memory_request_client_t::memory_operation, MEMORY_OPERATION_FREE, memory_size, opcode_address, orcs_engine, PACKAGE_STATE_FREE, processed, processor_id, memory_request_client_t::readyAt, readyToGo, rob_ptr, sent, memory_request_client_t::status, uop_executed, uop_number, wait_mem_deps_number, and waiting_DRAM.
printAllOrder()
void memory_order_buffer_line_t::printAllOrder (memory_order_buffer_line_t * input_array, uint32_t size_array, uint32_t start, uint32_t end) static
Definition at line 107 of file memory_order_buffer_line.cpp.
{
    uint32_t pos = start;
    for (uint32_t i = 0; i< used; i++){
        ORCS_PRINTF("%s\n",input_array[pos].content_to_string().c_str())
        pos++;
        if(pos>=size_array)pos=0;
    }
}
References content_to_string(), and ORCS_PRINTF.
Member Data Documentation
uop_executed
bool memory_order_buffer_line_t::uop_executed
Memory Dependencies Control.
rob pointer
Definition at line 21 of file memory_order_buffer_line.hpp.
The documentation for this class was generated from the following files:
processor/memory_order_buffer_line.hpp
processor/memory_order_buffer_line.cpp